Features for protocol parameters and protocol parameter updates
IntersectMBO/cardano-api pull request #182
Opened 2023-08-11 01:13 UTC by newhoggy

# Changelog

```yaml
- description: |
    <insert-changelog-description-here>
# uncomment types applicable to the change:
  type:
  # - feature        # introduces a new feature
  # - breaking       # the API has changed in a breaking way
  # - compatible     # the API has changed but is non-breaking
  # - optimisation   # measurable performance improvements
  # - improvement    # QoL changes e.g. refactoring
  # - bugfix         # fixes a defect
  # - test           # fixes/modifies tests
  # - maintenance    # not directly related to the code
  # - release        # related to a new release preparation
  # - documentation  # change in code docs, haddocks...
```

# Context

Additional context for the PR goes here.

If the PR fixes a particular issue please provide a
[link](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword=)
to the issue.

# Checklist

- [ ] Commit sequence broadly makes sense and commits have useful messages
- [ ] The change log section in the PR description has been filled in
- [ ] New tests are added if needed and existing tests are updated.  These may include:
  - golden tests
  - property tests
  - round trip tests
  - integration tests
  See [Running tests](https://github.com/input-output-hk/cardano-node-wiki/wiki/Running-tests) for more details
- [ ] The version bounds in `.cabal` files are updated
- [ ] CI passes. See note on CI.  The following CI checks are required:
  - [ ] Code is linted with `hlint`.  See `.github/workflows/check-hlint.yml` to get the `hlint` version
  - [ ] Code is formatted with `stylish-haskell`.  See `.github/workflows/stylish-haskell.yml` to get the `stylish-haskell` version
  - [ ] Code builds on Linux, MacOS and Windows for `ghc-8.10.7` and `ghc-9.2.7`
- [ ] The changelog section in the PR is updated to describe the change
- [ ] Self-reviewed the diff

2023-08-11 13:12 UTC, Jimbo4350 requested changes
I think this is more complicated than it needs to be

2023-08-11 14:19 UTC, carbolymer approved these changes

2023-08-12 01:01 UTC, newhoggy commented on cardano-api/internal/Cardano/Api/Domain/ProtocolParameters.hs
> +  }
The goal of this PR is to be as thin a layer around ledger types as possible.  To that `ProtocolParameters` is a `newtype` around the corresponding ledger type with not additional type structure.

That the `newtype` exists at all is so that we have the ability to control JSON and serialisation instances.

2023-08-14 11:59 UTC, newhoggy commented on cardano-api/internal/Cardano/Api/Domain/ProtocolParameters.hs
> +                <**>  ( inEraFeature era (pure id) $ \w -> do
Added `parseJsonFieldByEra` to do the deduplication.

2023-08-14 12:02 UTC, newhoggy commented on cardano-api/internal/Cardano/Api/Domain/ProtocolParameters.hs
> +emptyProtocolParameters w = shelleyBasedEraConstraints w $ ProtocolParameters Ledger.emptyPParams
Use the ledger to construct a default protocol parameters value.  Must be in `ShelleyBasedEra era` to do it.

2023-08-14 12:06 UTC, newhoggy commented on cardano-api/internal/Cardano/Api/Domain/ProtocolParameters.hs
> +protocolParamProtocolVersionL w = shelleyBasedEraConstraints w $ protocolParametersL . Ledger.ppProtocolVersionL
The rest of the file defines lenses which wrap the ledger one.

The context is that `cardano-api` uses GADT witnesses to decide whether an operation is valid in a given era  whereas `cardano-ledger` uses type class constraints.

The key idea is to take the ledger lenses which follow the ledger way and convert it into an api lens that uses the api way.

In order to do that, all we do is take a witness as an argument, use it to summon constraints and then using those constraints delegate to the ledger.

2023-08-14 12:09 UTC, newhoggy commented on cardano-api/internal/Cardano/Api/Domain/ProtocolParameters.hs
> +protocolParamExtraPraosEntropyL w = shelleyToAlonzoEraConstraints w $ protocolParametersL . Ledger.ppExtraEntropyL . unLedgerNonceL
If we ever want to expose an api type instead of a ledger type from our lenses, we can adjust them through lens composition.

2023-08-14 12:12 UTC, newhoggy commented on cardano-api/internal/Cardano/Api/Domain/ProtocolParameters.hs
> +          , "maxCollateralInputs"     .= justInEraFeature era (\w -> pp ^. protocolParamMaxCollateralInputsL w)
We can use `featureInEra` to generate `ToJSON` instances, but using `justInEraFeature` makes the code slightly shorter.

The nice thing here is we don't need to know what the type of the witness value `w`.  The lens function we choose determines that type for us.

Adding an extra field is just adding an extra line.

No decision needs to be made as to what type or constructor a field needs to be added to because we don't define any.  We just use the thin wrapper lenses.

If the ledger deprecates a field in the future, the only thing we need to adjust are the wrapper lenses.  This code will adapt accordingly with no changes.

2023-08-14 12:13 UTC, newhoggy commented on cardano-api/internal/Cardano/Api/Domain/ProtocolParameters.hs
> +        withObject "ProtocolParameters" $ \o -> do
This code is a little bit "interesting", but is understandable with explanation.

2023-08-14 12:15 UTC, newhoggy commented on cardano-api/internal/Cardano/Api/Domain/ProtocolParameters.hs
> +          pp <- inEraFeature era (fail ("Supported Era " <> show era)) (\w -> pure $ shelleyBasedEraConstraints w $ emptyProtocolParameters w)
The first thing is to generate a default `ProtocolParameters era` value.  The idea then is that for each potential field, we"mutate` this value to include and update to that field in the value.

2023-08-14 12:20 UTC, newhoggy commented on cardano-api/internal/Cardano/Api/Domain/ProtocolParameters.hs
> +              pure (emptyProtocolParameters sbe)
We generate a default protocol parameters value just like before.

2023-08-14 12:30 UTC, newhoggy commented on cardano-api/internal/Cardano/Api/Domain/ProtocolParameters.hs
> +                      )
The plan here is to do something analogous to this

```
defaultProtocolParameters
  & updateField1
  & updateField2
```

That is, we start with a default value of the type `ProtocolParameters era` then apply a function for each field that updates the value with the value for that field.

`updateField1` and `updateField2` have the type `ProtocolParameters era -> ProtocolParameters era`.

But we need to do this applicatively.

We can do this with the `<**>`.  This operator is exactly like the `<*>` operator but the arguments are reverse.

Observe:

(<*>) :: Applicative f => f (a -> b) -> f a -> f b
(<**>) :: Applicative f => f a -> f (a -> b) -> f b

What `<**>` allows us to do is write:

```
pure defaultProtocolParameters
  <**> updateField1
  <**> updateField2
```

And we are doing the exact same thing as the earlier example except applicatively which means this works with `optparse-applicative` and because every `Applicative` is a `Monad`, JSON parser works as well.

In the code , in each invocation of `<**>` we pass a value of the type `Parser (ProtocolParameters era -> ProtocolParameters era)`.

This parser will be `pure id` if the era is not supported.  If the era is supported however, we return a parser that mutates the `ProtocolParameter era` with an update to the relevant field.

2023-08-14 12:32 UTC, newhoggy commented on cardano-api/internal/Cardano/Api/Domain/ProtocolParameters.hs
> +                <**>  parseJsonFieldByEra era o "stakeAddressDeposit"   (\w v -> protocolParamStakeAddressDepositL  w .~ v)
The new `parseJsonFieldByEra` makes the code very pleasant.

Just like in the JSON printing case, JSON parsing is type-safe and era-sensitive.  The type `w` is automatically inferred to be whatever the lens we use demands.

If ledger changes removes the field in a future era, only the lens need change.  No change is required here.

2023-08-14 12:35 UTC, newhoggy commented on cardano-api/internal/Cardano/Api/Domain/ProtocolParameters.hs
> +                <**>  parseJsonFieldByEra era o "extraPraosEntropy"     (\w v -> protocolParamExtraPraosEntropyL    w .~ v)
As a demonstration of a deprecate field handling, `protocolParamExtraPraosEntropyL` which demands `ShelleyToAlonzoEra era`, which means it is already deprecated, but no special handling is needed here.  `parseJsonFieldByEra` does all the era-switching for us thanks to `FeatureInEra`.

2023-08-14 12:36 UTC, newhoggy commented on cardano-api/internal/Cardano/Api/Domain/ProtocolParameters.hs
> +                <**>  ( inEraFeature era (pure id) $ \w -> do
See https://github.com/input-output-hk/cardano-api/pull/182/commits/7e2d409086385df91acb3d8725056023e10b5746#r1293399395

2023-08-14 12:41 UTC, newhoggy commented on cardano-api/internal/Cardano/Api/Domain/ProtocolParameters.hs
> +                      )
One very relevant detail is in the context of `optparse-applicative` if the era is not supported and we use `pure id`, the CLI parser will recognise this as saying we do not accept a switch/argument so the CLI omits the unsupported CLI switch argument.

If the feature is supported an actual CLI parser that accepts the value for that field is return instead so the CLI help will include the field.

This is how the CLI can be made to be era-sensitive with very little maintenance work.

2023-08-14 14:09 UTC, Jimbo4350 requested changes
I'm currently working on `EraBasedProtocolParametersUpdate` to construct a `PParams era`. We can revisit this after to see which parts are still relevant.

2023-08-17 20:59 UTC, lehins commented on cardano-api/internal/Cardano/Api/Domain/ExecutionUnits.hs
> +data ExecutionUnits = ExecutionUnits
This could be a newtype around `ExUnits Nartural`

then all instances can be derived and conversion is just a `coerce`

2023-08-17 20:59 UTC, lehins commented on cardano-api/internal/Cardano/Api/Domain/ProtVer.hs
> +instance FromJSON ProtVer where
As mentioned in a private message this can be derived. The whole reason why json instances exist in ledger is for cardano-api

2023-08-17 20:59 UTC, lehins commented on cardano-api/internal/Cardano/Api/Feature/AlonzoEraOnly.hs
> +  , L.ShelleyEraTxCert (ShelleyLedgerEra era)
All of this are redundant:
```suggestion
  , L.AlonzoEraPParams (ShelleyLedgerEra era)
  , L.EraCrypto (ShelleyLedgerEra era) ~ L.StandardCrypto
  , L.EraTx (ShelleyLedgerEra era)
  , L.ExactEra L.AlonzoEra (ShelleyLedgerEra era)
  , L.HashAnnotated (L.TxBody (ShelleyLedgerEra era)) L.EraIndependentTxBody L.StandardCrypto
  , L.ShelleyEraTxBody (ShelleyLedgerEra era)
  , L.ShelleyEraTxCert (ShelleyLedgerEra era)
```


in fact you could probably get away with a single constraint here:
```
  , ShelleyLedgerEra era ~ L.Alonzo

2023-08-17 20:59 UTC, lehins commented on cardano-api/internal/Cardano/Api/Feature/AlonzoEraOnwards.hs
> +  , L.ShelleyEraTxCert (ShelleyLedgerEra era)
Redundant, since they are inherited by other constraints that already present
```suggestion
  , L.EraCrypto (ShelleyLedgerEra era) ~ L.StandardCrypto
  , L.EraPParams (ShelleyLedgerEra era)
  , L.EraTx (ShelleyLedgerEra era)
  , L.HashAnnotated (L.TxBody (ShelleyLedgerEra era)) L.EraIndependentTxBody L.StandardCrypto
  , L.ShelleyEraTxBody (ShelleyLedgerEra era)
  , L.ShelleyEraTxCert (ShelleyLedgerEra era)
```

2024-01-20 01:50 UTC, closed without merging