Implement `unsafeEraCastLedgerProtocolParameters`
IntersectMBO/cardano-api pull request #223
Opened 2023-08-31 13:56 UTC by newhoggy

# Changelog

```yaml
- description: |
    Implement `unsafeEraCastLedgerProtocolParameters`
# uncomment types applicable to the change:
  type:
  - feature        # introduces a new feature
  # - breaking       # the API has changed in a breaking way
  # - compatible     # the API has changed but is non-breaking
  # - optimisation   # measurable performance improvements
  # - improvement    # QoL changes e.g. refactoring
  # - bugfix         # fixes a defect
  # - test           # fixes/modifies tests
  # - maintenance    # not directly related to the code
  # - release        # related to a new release preparation
  # - documentation  # change in code docs, haddocks...
```

# Context

`unsafeEraCastLedgerProtocolParameters` will case `LedgerProtocolParameters` from any shelley-based era to any other shelley-based era.

As noted in the comments, the function is unsafe and its use in inadvisable.

However, I would like to merge this PR for two reasons:

* It provides an example of how to use `Applicative` to construct ledger values.  An inclusion of an example in `cardano-api` will be useful for implementing safe functionality for other ledger types.  And since this is the first such example written for `cardano-api` it ought to be included for that purpose.
* I have some ideas on how expose unsafe functionality in `cardano-cli` in a principled manner and would like to use this to try it out.  This doesn't necessarily have any bearing on whether _this_ functionality will be exposed, but there are other technically unsafe operations _we do want to expose_ (era-upgrade of transactions for example) so we want to have the ability to expose unsafe functionality from `cardano-cli` in general.  Doing it for this functionality could prove a useful proof of concept.

To ensure the function is not abused, it has been appropriately prefixed with the word `unsafe`.

We can later decide after more supporting code is written and merged that we definitely do not want this functionality and delete it at that point.

This uses newly defined features in `Cardano.Api.Features.*` to automatically determine if a field can be casted.

# Checklist

- [ ] Commit sequence broadly makes sense and commits have useful messages
- [ ] The change log section in the PR description has been filled in
- [ ] New tests are added if needed and existing tests are updated.  These may include:
  - golden tests
  - property tests
  - round trip tests
  - integration tests
  See [Running tests](https://github.com/input-output-hk/cardano-node-wiki/wiki/Running-tests) for more details
- [ ] The version bounds in `.cabal` files are updated
- [ ] CI passes. See note on CI.  The following CI checks are required:
  - [ ] Code is linted with `hlint`.  See `.github/workflows/check-hlint.yml` to get the `hlint` version
  - [ ] Code is formatted with `stylish-haskell`.  See `.github/workflows/stylish-haskell.yml` to get the `stylish-haskell` version
  - [ ] Code builds on Linux, MacOS and Windows for `ghc-8.10.7` and `ghc-9.2.7`
- [ ] The changelog section in the PR is updated to describe the change
- [ ] Self-reviewed the diff

2023-08-31 13:56 UTC, newhoggy commented on cardano-api/internal/Cardano/Api/ProtocolParameters.hs
> +      pure $ LedgerProtocolParameters npp
Like magic!

2023-08-31 14:10 UTC, carbolymer commented on cardano-api/internal/Cardano/Api/Eras/Core.hs
> +  -> (feature era1 -> feature era2 -> a)  -- ^ Function to get thealue to use if the feature is supported in the era
typo in `thealue`

2023-08-31 14:10 UTC, carbolymer commented on cardano-api/internal/Cardano/Api/Eras/Core.hs
> +  => (feature era -> a)   -- ^ Function to get thealue to use if the feature is supported in the era
typo in `thealue`

2023-08-31 14:11 UTC, carbolymer commented on cardano-api/internal/Cardano/Api/Eras/Core.hs
> +  -> (feature era -> a)   -- ^ Function to get thealue to use if the feature is supported in the era
same typo as above

2023-08-31 14:16 UTC, carbolymer commented on cardano-api/internal/Cardano/Api/ProtocolParameters.hs
> +        <**>  in2ErasFeature src tgt (Left eraCastError) (\wSrc wTgt -> pure $ \pp -> pp & Domain.protocolParamUTxOCostPerByteL     wTgt  .~ (opp ^. Domain.protocolParamUTxOCostPerByteL     wSrc))
would it be possible to deduplicate this and reduce the number of lambdas used?

2023-08-31 14:20 UTC, newhoggy commented on cardano-api/internal/Cardano/Api/ProtocolParameters.hs
> +        <**>  in2ErasFeature src tgt (Left eraCastError) (\wSrc wTgt -> pure $ \pp -> pp & Domain.protocolParamUTxOCostPerByteL     wTgt  .~ (opp ^. Domain.protocolParamUTxOCostPerByteL     wSrc))
I think so, but I think it can easily be a separate PR because doing so doesn't change the public interface.

2023-09-01 07:45 UTC, carbolymer submitted a review, later dismissed
Vide: https://input-output-rnd.slack.com/archives/C057E9CJTPH/p1693494111115739 - eracasting of ledger protocol params is not needed, we need to support only matching eras

2023-09-04 08:45 UTC, carbolymer commented on cardano-api/internal/Cardano/Api/ProtocolParameters.hs
> +-- | This instance of era cast will not fail if the target era is a shelley based era.  If the
I think that's not an instance anymore

2023-09-04 08:53 UTC, carbolymer reviewed
@newhoggy even when we don't want to support era casting, what would be a use case for `unsafeEraCastLedgerProtocolParameters`? This function introduces bunch of code, which will require future maintenance.
The current use case of making sure that CLI era and node's eras matches can be satisfied just testing equality of two eras.

2023-09-04 13:48 UTC, Jimbo4350 requested changes
The plan is the not support casting anymore. Users are expected to update the cli to the latest version.

2024-01-19 01:50 UTC, closed without merging