Reading ShelleyNTC when querying node
IntersectMBO/cardano-api pull request #403
Opened 2023-12-15 17:58 UTC by carbolymer

# Changelog

```yaml
- description: |
    <insert-changelog-description-here>
# uncomment types applicable to the change:
  type:
  # - feature        # introduces a new feature
  # - breaking       # the API has changed in a breaking way
  # - compatible     # the API has changed but is non-breaking
  # - optimisation   # measurable performance improvements
  # - improvement    # QoL changes e.g. refactoring
  # - bugfix         # fixes a defect
  # - test           # fixes/modifies tests
  # - maintenance    # not directly related to the code
  # - release        # related to a new release preparation
  # - documentation  # change in code docs, haddocks...
```

# Context

Additional context for the PR goes here. If the PR fixes a particular issue please provide a [link](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword=) to the issue.

# How to trust this PR

Highlight important bits of the PR that will make the review faster. If there are commands the reviewer can run to observe the new behavior, describe them.

# Checklist

- [ ] Commit sequence broadly makes sense and commits have useful messages
- [ ] New tests are added if needed and existing tests are updated. See [Running tests](https://github.com/input-output-hk/cardano-node-wiki/wiki/Running-tests) for more details
- [ ] Self-reviewed the diff

2023-12-22 15:18 UTC, carbolymer commented on cardano-api/internal/Cardano/Api/IPC/Monad.hs
> +      | otherwise -> pure . Left $ UnsupportedNtcVersionError minNtcVersion ntcVersion
* [ ] TODO: include shelley NTC version info and/or use separate error for it

2023-12-22 18:53 UTC, Jimbo4350 requested changes
I haven't look at this yet but I'm prematurely requesting changes as this needs to be carefully considered.

2024-01-04 19:15 UTC, amesgen reviewed
The new logic here looks correct to me.

We also talked about this in the Consensus Office Hours today, and came to the conclusion that we can avoid `cardano-api` having to implement this more complicated logic by a simple change in Consensus, see #863 and #862.

2024-01-08 12:58 UTC, carbolymer commented
Thanks @amesgen ! I think I prefer to rely on the consensus change and your assumption:
```
In order to reduce the number of possible version combinations, we currently follow the convention that all `ShelleyNodeToClientVersion`s in one `CardanoNodeToClientVersionX` are equal.
```
this way we can just use `NodeToClientVersion` and avoid introducing redundant code.
@Jimbo4350 thoughts?

2024-02-01 16:41 UTC, carbolymer commented
Closing because of: https://github.com/IntersectMBO/cardano-api/pull/403#issuecomment-1880960379

2024-02-01 16:41 UTC, closed without merging