Add return value to `checkLedgerStateCondition`
IntersectMBO/cardano-api pull request #433
Opened 2024-01-23 14:45 UTC by carbolymer

# Changelog

```yaml
- description: |
    Add return value to `checkLedgerStateCondition`
# uncomment types applicable to the change:
  type:
  # - feature        # introduces a new feature
   - breaking       # the API has changed in a breaking way
  # - compatible     # the API has changed but is non-breaking
  # - optimisation   # measurable performance improvements
  # - improvement    # QoL changes e.g. refactoring
  # - bugfix         # fixes a defect
  # - test           # fixes/modifies tests
  # - maintenance    # not directly related to the code
  # - release        # related to a new release preparation
  # - documentation  # change in code docs, haddocks...
```

# Context

This change allows to return any value from `checkLedgerStatecondition`, for example it will be possible to access ledger state.

# Checklist

- [ ] Commit sequence broadly makes sense and commits have useful messages
- [ ] New tests are added if needed and existing tests are updated. See [Running tests](https://github.com/input-output-hk/cardano-node-wiki/wiki/Running-tests) for more details
- [ ] Self-reviewed the diff

2024-01-23 14:50 UTC, carbolymer commented on cardano-api/internal/Cardano/Api/LedgerState.hs
> +                                    (ConditionNotMet, _) -> return $ clientIdle_RequestMoreN newClientTip newServerTip n knownLedgerStates'
This is wrong, we're dropping result from `condition` here.

2024-01-23 15:49 UTC, smelc commented on cardano-api/internal/Cardano/Api/LedgerState.hs
> +    _ -> Nothing
```suggestion
  listToMaybe epochs
```

Optional. I like explicitness too :upside_down_face:

2024-01-24 14:53 UTC, Jimbo4350 requested changes

2024-01-24 14:53 UTC, Jimbo4350 commented on cardano-api/internal/Cardano/Api/LedgerState.hs
> +  -> a
What use cases do you envision for this?

2024-01-24 14:57 UTC, carbolymer commented on cardano-api/internal/Cardano/Api/LedgerState.hs
> +  -> a
Allowing to get out information from the `LedgerState`.

2024-01-26 10:55 UTC, carbolymer commented on cardano-api/internal/Cardano/Api/LedgerState.hs
> +  listToMaybe epochs
```suggestion
  listToMaybe 
    [ currentEpoch' | PoolReap poolReapDets <- events
    , let currentEpoch' = prdEpochNo poolReapDets
    , currentEpoch' >= terminationEpoch
    ]
```

2024-01-26 10:55 UTC, carbolymer commented on cardano-api/internal/Cardano/Api/LedgerState.hs
> +  listToMaybe epochs
```suggestion
  listToMaybe 
    [ currentEpoch' | PoolReap poolReapDets <- events
    , let currentEpoch' = prdEpochNo poolReapDets
    , currentEpoch' >= terminationEpoch
    ]
```

2024-01-26 14:55 UTC, Jimbo4350 approved these changes
LGTM!

2024-01-26 14:55 UTC, Jimbo4350 commented on cardano-api/internal/Cardano/Api/LedgerState.hs
> +  -> ( AnyNewEpochState -- ^ current epoch state
Much cleaner IMO :+1:

2024-01-26 14:55 UTC, Jimbo4350 commented on cardano-api/internal/Cardano/Api/LedgerState.hs
> +import           Control.Monad.State.Strict
:+1:

2024-01-26 14:55 UTC, Jimbo4350 commented on cardano-api/internal/Cardano/Api/LedgerState.hs
> +                                (r, condition)
Thoughts on these variable renames?
```diff
diff --git a/cardano-api/internal/Cardano/Api/LedgerState.hs b/cardano-api/internal/Cardano/Api/LedgerState.hs
index 1f7c11234..57281d0e7 100644
--- a/cardano-api/internal/Cardano/Api/LedgerState.hs
+++ b/cardano-api/internal/Cardano/Api/LedgerState.hs
@@ -2008,9 +2008,9 @@ checkLedgerStateCondition nodeConfigFilePath socketPath validationMode terminati
                               in clientIdle_DoneNwithMaybeError n err
                             Right lState -> do
                               let newEpochState = AnyNewEpochState sbe lState
-                              condition <- atomicModifyIORef' stateIORef $ \(_, result) -> do
-                                let r@(!condition, !_) = runState (checkCondition newEpochState) result
-                                (r, condition)
+                              condition <- atomicModifyIORef' stateIORef $ \(_prevCondition, previousState) -> do
+                                let updatedState@(!newCondition, !_) = runState (checkCondition newEpochState) previousState
+                                (updatedState, newCondition)
                               -- Have we reached the termination epoch?
                               case atTerminationEpoch terminationEpoch ledgerEvents of
                                 Just !currentEpoch -> do
```

2024-01-29 17:09 UTC, merged