Release cardano-api-8.45.0.0
IntersectMBO/cardano-api pull request #518
Opened 2024-04-12 08:35 UTC by smelc

# Changelog

```yaml
- description: |
    Release cardano-api-8.45.0.0
# uncomment types applicable to the change:
  type:
  # - feature        # introduces a new feature
  # - breaking       # the API has changed in a breaking way
  # - compatible     # the API has changed but is non-breaking
  # - optimisation   # measurable performance improvements
  # - improvement    # QoL changes e.g. refactoring
  # - bugfix         # fixes a defect
  # - test           # fixes/modifies tests
  # - maintenance    # not directly related to the code
  - release        # related to a new release preparation
  # - documentation  # change in code docs, haddocks...
```

# Context

CHaP PR: https://github.com/IntersectMBO/cardano-haskell-packages/pull/742

2024-04-12 09:29 UTC, carbolymer commented on cardano-api/CHANGELOG.md
> +- - Add `getReferenceInputsSizeForTxIds` function.
This shouldn't be in changelog as it was released previously. Is it a bug in the changelog script?

2024-04-12 09:57 UTC, carbolymer requested changes
Redundant entry in changelog

2024-04-12 10:10 UTC, smelc commented on cardano-api/CHANGELOG.md
> +- - Add `getReferenceInputsSizeForTxIds` function.
Good catch, this probably comes from this interleaving: 

![image](https://github.com/IntersectMBO/cardano-api/assets/634720/5bd60cf9-0116-415e-9377-25e7846db081)

2024-04-12 10:20 UTC, carbolymer commented on cardano-api/CHANGELOG.md
> +- - Add `getReferenceInputsSizeForTxIds` function.
Linearized view of GH commits is ass.
![image](https://github.com/IntersectMBO/cardano-api/assets/228866/33f02e41-2fd8-428d-92bf-3ccc9dc5bb3e)
Yeah. Seems that the script looked at `428fa68e4` or `296a61656` but they aren't children of 8.44 tag `530d44384` so they shouldn't be taken into account.

2024-04-12 12:49 UTC, smelc commented on cardano-api/CHANGELOG.md
> +- - Add `getReferenceInputsSizeForTxIds` function.
This is caused by `git log`'s behavior:

```
       List commits that are reachable by following the parent links from the given commit(s), but exclude commits
       that are reachable from the one(s) given with a ^ in front of them.

       A special notation "<commit1>..<commit2>" can be used as a short-hand for "^<commit1> <commit2>".
```

So in this case the script executes `git log --merges --oneline "cardano-api-8.44.0.0..HEAD"` i.e.:

```
git log --merges --oneline ^cardano-api-8.44.0.0 HEAD
```

And indeed, `428fa68e4` is a parent of `HEAD` that is not a parent of `cardano-api-8.44.0.0`, so it gets listed. What we want is the list of commits between the two commits we give, not git log's behavior of using the parent link.

2024-04-12 12:53 UTC, smelc commented on cardano-api/CHANGELOG.md
> +- - Add `getReferenceInputsSizeForTxIds` function.
I believe we need to add [--ancestry-path](https://git-scm.com/docs/git-log#Documentation/git-log.txt---ancestry-pathltcommitgt) to our `git log` invokation.

2024-04-15 10:12 UTC, merged

2024-04-15 12:40 UTC, smelc commented
PR updating API in CLI: https://github.com/IntersectMBO/cardano-cli/pull/720