Adds new query for a snapshot of big ledger peers
IntersectMBO/cardano-api pull request #521
Opened 2024-04-18 07:33 UTC by crocodile-dentist

This change introduces a new query tag and handler to support retrieval of a snapshot of big ledger peers from the current tip of a node.

# Changelog

```yaml
- description: |
    Added `GetPeerSnapshot` block query
# uncomment types applicable to the change:
  type:
  - feature        # introduces a new feature
  # - breaking       # the API has changed in a breaking way
  # - compatible     # the API has changed but is non-breaking
  # - optimisation   # measurable performance improvements
  # - improvement    # QoL changes e.g. refactoring
  # - bugfix         # fixes a defect
  # - test           # fixes/modifies tests
  # - maintenance    # not directly related to the code
  # - release        # related to a new release preparation
  # - documentation  # change in code docs, haddocks...
```

# Context

A snapshot of big ledger peers is very useful when bootstrapping a node from scratch in the upcoming Genesis consensus mode. Since only some, or none, of these peers are available to a node from its own ledger when syncing up, a snapshot is a means of providing these relays to the diffusion layer to ensure that a node ends up on a good chain.

# Checklist

- [ ] Commit sequence broadly makes sense and commits have useful messages
- [ ] New tests are added if needed and existing tests are updated. See [Running tests](https://github.com/input-output-hk/cardano-node-wiki/wiki/Running-tests) for more details
- [ ] Self-reviewed the diff

2024-04-18 16:22 UTC, carbolymer commented on cardano-api/CHANGELOG.md
> +
This is not needed. `CHANGELOG.md` is a generated file.
```suggestion
```

2024-04-18 16:30 UTC, carbolymer requested changes
Good work, thanks. Few comments to make sure that this PR adheres to the conventions used here.

There are build failures too.

2024-04-18 16:30 UTC, carbolymer commented on cardano-api/internal/Cardano/Api/Query.hs
> +
This should be similarly era-cased to the other commands. That's our client-side check for era when executing a query. I understand this is only available for Conway onwards, correct?
```suggestion
    caseShelleyToBabbageOrConwayEraOnwards
    (const $ error "toConsensusQueryShelleyBased: QueryLedgerPeerSnapshot is only available in the Conway era")
    (const $ Some (consensusQueryInEraInMode era (Consensus.GetCBOR Consensus.GetPeerSnapshot)))
    sbe
    

```

2024-04-18 16:30 UTC, carbolymer commented on cardano-api/internal/Cardano/Api/Query.hs
> +      Consensus.GetCBOR Consensus.GetPeerSnapshot -> r'
A more meaningful variable name than `r'` would be nice here.

2024-04-18 16:30 UTC, carbolymer commented on cardano-api/internal/Cardano/Api/Query/Expr.hs
> +  => ShelleyBasedEra era
This should be something different than `ShelleyBasedEra era`. Again, this is our client-level safeguard against trying to use a command in an unsupported era. This time it's a type-level check. 😄 
If it is a Conway onwards command use `ConwayEraOnwards` or pick any other suitable eon from there: https://github.com/IntersectMBO/cardano-api/tree/main/cardano-api/internal/Cardano/Api/Eon

2024-04-18 16:38 UTC, carbolymer approved these changes
Actually, not blocking changes if this query is for eras >= Shelley.

2024-07-05 18:16 UTC, palas commented
FYI: Because we now enforce the use of `cabal-gild` to format cabal files and, in order to reduce the amount of hassle, I have cherry-picked the appropriate commit into your PR. This will make the `cabal-gild` CI check pass for the PR. The commit should be discarded automatically as soon as you either rebase or merge the PR (since it is already in the `main` branch). Feel free to discard it if you want, but that will make the new required action to fail until you rebase.

2024-07-06 02:18 UTC, palas commented
FYI: I have rebased your branch because we have done changes to the formatting. I have made a copy of the unrebased branch here: [backup/mwojtowicz/query-ledger-peer-snapshot](https://github.com/IntersectMBO/cardano-api/tree/backup/mwojtowicz/query-ledger-peer-snapshot)

2024-11-14 12:46 UTC, carbolymer approved these changes
LGTM. Can you test e2e (with cardano-cli changes) if the query works, before merging?

2024-11-14 12:46 UTC, carbolymer commented on cabal.project
> +source-repository-package
SRP needs to be removed before merge.

2025-01-10 07:45 UTC, carbolymer commented on cardano-api/internal/Cardano/Api/Query/Expr.hs
> +  queryExpr $ QueryInEra $ QueryInShelleyBasedEra sbe QueryLedgerPeerSnapshot
If it's a query introduced in Conway, then it needs to be `ConwayEraOnwards`:
```haskell
queryLedgerPeerSnapshot
  :: ()
  => ConwayEraOnwards era
  -> LocalStateQueryExpr
      block
      point
      QueryInMode
      r
      IO
      (Either UnsupportedNtcVersionError (Either EraMismatch (Serialised LedgerPeerSnapshot)))
queryLedgerPeerSnapshot ceo =
  queryExpr $ QueryInEra $ QueryInShelleyBasedEra (convert ceo) QueryLedgerPeerSnapshot
```

2025-01-10 10:51 UTC, carbolymer commented on cardano-api/internal/Cardano/Api/Query/Expr.hs
> +  queryExpr $ QueryInEra $ QueryInShelleyBasedEra sbe QueryLedgerPeerSnapshot
Actually, it does not make sense. `ShelleyBasedEra` is ok here. We don't need to restrict the new query to Conway.

2025-01-10 12:58 UTC, carbolymer approved these changes

2025-01-13 08:11 UTC, crocodile-dentist commented
I've tested the query on a live node and it functions as expected - this is ready to be merged.

2025-01-14 11:13 UTC, merged