evaluateTransactionExecutionUnitsShelley: return logs
IntersectMBO/cardano-api pull request #555
Opened 2024-06-14 08:32 UTC by smelc

# Changelog

```yaml
- description: |
    evaluateTransactionExecutionUnitsShelley: return logs that are useful for debugging
# uncomment types applicable to the change:
  type:
  # - feature        # introduces a new feature
  - breaking       # the API has changed in a breaking way
  # - compatible     # the API has changed but is non-breaking
  # - optimisation   # measurable performance improvements
  # - refactoring    # QoL changes
  # - bugfix         # fixes a defect
  # - test           # fixes/modifies tests
  # - maintenance    # not directly related to the code
  # - release        # related to a new release preparation
  # - documentation  # change in code docs, haddocks...
```

# Context

This was asked by a user [here on Slack](https://input-output-rnd.slack.com/archives/G011N23CEAE/p1717012833898899) and it makes sense, since existing callers can just ignore the new logs that are being returned; taking advantage of Haskell's lazyness.

# How to trust this PR

It's returning more data

# Checklist

- [X] Commit sequence broadly makes sense and commits have useful messages
- [X] Self-reviewed the diff

2024-06-14 15:15 UTC, palas approved these changes
You're right, it looks like `evalTxExUnits` just uses `evalTxExUnitsWithLogs` anyway.
I just wrote a stylistic suggestion.

2024-06-14 15:15 UTC, palas commented on cardano-api/internal/Cardano/Api/Fees.hs
> +            (Map ScriptWitnessIndex (Either ScriptExecutionError ([Text.Text], ExecutionUnits)))
I would import the constructor like this: `import Data.Text (Text)` and then just write `Text` everywhere instead of `Text.Text`. It is already done like this with `Map`.

I am also aware that, before your PR, there was already a case where it was done like `Text.Text` too, so you are following the pattern either way.

2024-06-14 16:52 UTC, Jimbo4350 requested changes
Nice :+1: . I agree with @palas's comment

2024-06-14 16:52 UTC, Jimbo4350 commented on cardano-api/internal/Cardano/Api/Fees.hs
> +            (Map ScriptWitnessIndex (Either ScriptExecutionError ([Text.Text], ExecutionUnits)))
A type annotation isn't strictly necessary but it wouldn't hurt here.

2024-06-17 07:44 UTC, smelc commented on cardano-api/internal/Cardano/Api/Fees.hs
> +            (Map ScriptWitnessIndex (Either ScriptExecutionError ([Text.Text], ExecutionUnits)))
@palas> done the change :+1:

2024-06-17 07:47 UTC, smelc commented on cardano-api/internal/Cardano/Api/Fees.hs
> +            (Map ScriptWitnessIndex (Either ScriptExecutionError ([Text.Text], ExecutionUnits)))
@Jimbo4350> do you mean something like:

```hs
type TransactionExecutionUnits = Map ScriptWitnessIndex (Either ScriptExecutionError ([Text], ExecutionUnits))
```

and using `TransactionExecutionUnits` in `evaluateTransactionExecutionUnits`?

2024-06-17 10:10 UTC, Jimbo4350 approved these changes

2024-06-17 10:10 UTC, Jimbo4350 commented on cardano-api/internal/Cardano/Api/Fees.hs
> +            (Map ScriptWitnessIndex (Either ScriptExecutionError ([Text], ExecutionUnits)))
A type synonym for `[Text]` would aid in readability

2024-06-17 15:53 UTC, smelc commented on cardano-api/internal/Cardano/Api/Fees.hs
> +            (Map ScriptWitnessIndex (Either ScriptExecutionError ([Text], ExecutionUnits)))
@Jimbo4350> added type synonym `EvalTxExecutionUnitsLog`.

2024-06-18 07:02 UTC, Jimbo4350 commented on cardano-api/internal/Cardano/Api/Fees.hs
> +      -> Map ScriptWitnessIndex (Either ScriptExecutionError ([Text.Text], ExecutionUnits))
Here as well.

2024-06-18 07:02 UTC, Jimbo4350 approved these changes

2024-06-18 07:29 UTC, Jimbo4350 commented on cardano-api/internal/Cardano/Api/Fees.hs
> +           bimap (fromAlonzoScriptExecutionError aOnwards) (second fromAlonzoExUnits) exunitsOrFailure)
You can actually use `fmap` here instead of `second`.

2024-06-18 08:38 UTC, smelc commented on cardano-api/internal/Cardano/Api/Fees.hs
> +           bimap (fromAlonzoScriptExecutionError aOnwards) (second fromAlonzoExUnits) exunitsOrFailure)
I rather not generalize this code that is involved already. I think `second` better conveys the intent :+1:

2024-06-18 10:22 UTC, merged