queryStateForBalancedTx: return current treasury value
IntersectMBO/cardano-api pull request #557
Opened 2024-06-19 08:17 UTC by smelc

# Changelog

```yaml
- description: |
    Make the query used by the CLI's `transaction build` return the current treasury value, so that command to do treasury donation doesn't require the user to pass it. Corresponding CLI PR: https://github.com/IntersectMBO/cardano-cli/pull/778
# uncomment types applicable to the change:
  type:
  - feature        # introduces a new feature
  - breaking       # the API has changed in a breaking way
  # - compatible     # the API has changed but is non-breaking
  # - optimisation   # measurable performance improvements
  # - refactoring    # QoL changes
  # - bugfix         # fixes a defect
  # - test           # fixes/modifies tests
  # - maintenance    # not directly related to the code
  # - release        # related to a new release preparation
  # - documentation  # change in code docs, haddocks...
```

# Context

Required for `transaction build` not to perform a new call to retrieve the treasury's current value in https://github.com/IntersectMBO/cardano-cli/pull/778

# How to trust this PR

It returns additional data. Existing data is unchanged.

# Checklist

- [ ] Commit sequence broadly makes sense and commits have useful messages
- [ ] Self-reviewed the diff

2024-06-26 10:50 UTC, carbolymer commented on cardano-api/internal/Cardano/Api/Convenience/Query.hs
> +  deriving Show
I think this could be more readable
```suggestion
  deriving newtype Show
```

2024-06-26 10:54 UTC, carbolymer commented on cardano-api/internal/Cardano/Api/Query/Expr.hs
> +  => ShelleyBasedEra era
Are you sure about this witness? If it's in `>= v16`, shouldn't there be `ConwayEraOnwards era`?

2024-06-26 10:55 UTC, carbolymer approved these changes

2024-06-26 11:00 UTC, carbolymer commented on cardano-api/internal/Cardano/Api/Query/Expr.hs
> +  => ShelleyBasedEra era
This should `>=` Conway afaik.

2024-06-26 11:01 UTC, carbolymer requested changes
https://github.com/IntersectMBO/cardano-api/pull/557/files#r1654608157

2024-06-26 12:39 UTC, Jimbo4350 approved these changes
LGTM but you need to make the change suggested by @carbolymer

2024-06-26 19:06 UTC, smelc commented on cardano-api/internal/Cardano/Api/Query/Expr.hs
> +  => ShelleyBasedEra era
@carbolymer, @Jimbo4350> So then I should return a `Maybe TxTreasuryValue` in `queryStateForBalancedTx`?

And not include it if the era is before Conway in `transaction build` in CLI?

2024-06-27 07:52 UTC, carbolymer commented on cardano-api/internal/Cardano/Api/Query/Expr.hs
> +  => ShelleyBasedEra era
That would make most sense. Or use `Maybe (Featured ConwayEraOnwards era TxTreasuryValue)` to signal when treasury is present.

2024-06-27 09:54 UTC, smelc commented on cardano-api/internal/Cardano/Api/Query/Expr.hs
> +  => ShelleyBasedEra era
@carbolymer> did the change in the third commit `queryStateForBalancedTx: return Maybe (Featured ConwayEraOnwards era TxTreasuryValue` :+1:

2024-06-27 10:01 UTC, carbolymer approved these changes

2024-06-27 11:14 UTC, merged