Add cabal-gild and update hook
IntersectMBO/cardano-api pull request #578
Opened 2024-07-03 17:00 UTC by palas

# Changelog

```yaml
- description: |
    Added cabal-gild to dev shell, to haskell-style-lint hook script, and created CI action to check it.
  type:
    - maintenance
```

# Context

We don't want to have to worry about the formatting of `.cabal` files, and we want it to be consistent. This PR tries to address this.

# How to trust this PR

Probably check that the hook works for you. Also that you are happy with the changes and configuration, and that the CI passes.

# Checklist

- [x] Commit sequence broadly makes sense and commits have useful messages
- [x] New tests are added if needed and existing tests are updated. See [Running tests](https://github.com/input-output-hk/cardano-node-wiki/wiki/Running-tests) for more details
- [x] Self-reviewed the diff

2024-07-04 10:10 UTC, smelc commented on .github/workflows/check-cabal-gild.yml
> +        git --no-pager diff --exit-code
```suggestion
        rc="0"
        
        for file in $(git ls-files "*.cabal")
        do
          echo "cabal-gild --mode=check --input=$file"
          if ! cabal-gild --mode=check --input="$file"
          then
            echo "💣 $file is badly formatted. Fix it with:"
            echo "cabal-gild --mode=format --io=$file"
            rc="1"
          fi
        done
        
        exit $rc
```

Rationale:

1. Less git magic: either to understand, and so to maintain
2. Provides the command to fix the problem, instead of showing the diff; so easier to put into action

2024-07-04 10:40 UTC, carbolymer requested changes
Blocking on misaligned comments in the cabal file.

2024-07-04 10:40 UTC, carbolymer commented on .github/workflows/check-cabal-gild.yml
> +        version="${{env.CARDANO_GUILD_VERSION}}"
If we have cabal gild in nix shell, I think it would be better to use the one from nix. We wouldn't have to keep the two versions (gha and nix shell) in sync.

2024-07-04 10:40 UTC, carbolymer commented on cardano-api/cardano-api.cabal
> +  if impl(ghc == 8.10.7)&& os(darwin)&& arch(aarch64)
huh this one's weird with `&&` shifted to the left. But I guess we can live with that.

2024-07-04 10:40 UTC, carbolymer commented on cardano-api/cardano-api.cabal
> +    -- in this module
Oh no this is wrong. This comment was over the orphans module.
1. This comment is outdated - should be removed.
2. How does cabal-gild handle such comments? Was this a fluke, or those comments will always be moved to the top?
3. What about comments in the same line after the module - what happens with them? e.g.
  ```
  Cardano.Api.Address -- something something
  ```

2024-07-04 10:40 UTC, carbolymer commented on cardano-api/cardano-api.cabal
> +    -- exposed by cardano-api-ledger
Again, comment in the wrong place. I'm not sure if this one is up to date. I think you should consult with @Jimbo4350 this one.

2024-07-04 15:09 UTC, palas commented on .github/workflows/check-cabal-gild.yml
> +      fail-fast: false
No, I just copied it from the stylish-haskell workflow. I will delete it then

2024-07-04 15:11 UTC, palas commented on .github/workflows/check-cabal-gild.yml
> +        git --no-pager diff --exit-code
Nice. Yes, it is two files so, no need to optimize.

2024-07-04 15:15 UTC, palas commented on cardano-api/cardano-api.cabal
> +    -- in this module
You are right. I will try that. And I will check how `cabal-fmt` does it. Otherwise we can qualify the comment, even it is not ideal

2024-07-04 15:26 UTC, palas commented on cardano-api/cardano-api.cabal
> +    -- in this module
Nice, the inline comments worked!

2024-07-04 15:38 UTC, palas commented on cardano-api/cardano-api.cabal
> +  if impl(ghc == 8.10.7)&& os(darwin)&& arch(aarch64)
`cabal-fmt` looks nicer:
```
if ((impl(ghc ==8.10.7) && os(osx)) && arch(aarch64))
```

2024-07-04 15:43 UTC, palas commented on cardano-api/cardano-api.cabal
> +    -- in this module
`cabal-fmt` puts them in the end instead, same issue

2024-07-05 06:35 UTC, Jimbo4350 approved these changes

2024-07-05 06:35 UTC, Jimbo4350 commented on cardano-api/cardano-api.cabal
> +    -- exposed by cardano-api-ledger
We can remove the comment.

2024-07-05 17:45 UTC, merged