Make it build with ghc-9.10
IntersectMBO/cardano-api pull request #599
Opened 2024-07-29 01:22 UTC by erikd

# Changelog

```yaml
- description: |
    Support ghc-9.10
# uncomment types applicable to the change:
  type:
  # - maintenance    # not directly related to the code
```

# Context

# How to trust this PR

# Checklist

- [x] Commit sequence broadly makes sense and commits have useful messages
- [ ] New tests are added if needed and existing tests are updated. See [Running tests](https://github.com/input-output-hk/cardano-node-wiki/wiki/Running-tests) for more details
- [x] Self-reviewed the diff

2024-07-29 07:03 UTC, Jimbo4350 approved these changes
LGTM, devx will need to sort out CI.

2024-07-29 10:30 UTC, carbolymer commented on .github/workflows/haskell.yml
> +        ghc: ["8.10.7", "9.6.4", "9.8.2", "9.10.1"]
do we need to pin the patch version?
```suggestion
        ghc: ["8.10.7", "9.6.4", "9.8.2", "9.10"]
```

2024-07-29 10:31 UTC, carbolymer requested changes

2024-07-29 10:31 UTC, carbolymer commented on cardano-api/cardano-api.cabal
> +version: 9.2.0.0
Unnecessary version bump. We're only bumping version when releasing.

2024-07-30 03:21 UTC, erikd commented on cardano-api/cardano-api.cabal
> +version: 9.2.0.0
Have remove that commit from the PR.

2024-07-30 08:33 UTC, carbolymer approved these changes
LGTM

2024-08-05 21:56 UTC, merged