Update experimental api and propagate
IntersectMBO/cardano-api pull request #604
Opened 2024-07-31 08:48 UTC by Jimbo4350

# Changelog

```yaml
- description: |
    Update experimental api and propagate 
# uncomment types applicable to the change:
  type:
  - feature        # introduces a new feature
  # - breaking       # the API has changed in a breaking way
  # - compatible     # the API has changed but is non-breaking
  # - optimisation   # measurable performance improvements
  # - refactoring    # QoL changes
  # - bugfix         # fixes a defect
  # - test           # fixes/modifies tests
  # - maintenance    # not directly related to the code
  # - release        # related to a new release preparation
  # - documentation  # change in code docs, haddocks...
```

# Context

Additional context for the PR goes here. If the PR fixes a particular issue please provide a [link](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword=) to the issue.

# How to trust this PR

Highlight important bits of the PR that will make the review faster. If there are commands the reviewer can run to observe the new behavior, describe them.

# Checklist

- [ ] Commit sequence broadly makes sense and commits have useful messages
- [ ] New tests are added if needed and existing tests are updated. See [Running tests](https://github.com/input-output-hk/cardano-node-wiki/wiki/Running-tests) for more details
- [ ] Self-reviewed the diff

2024-07-31 14:52 UTC, carbolymer requested changes
Blocking to have more time to review. I'd like to to play with it a bit.

2024-08-08 12:13 UTC, carbolymer commented on cardano-api/internal/Cardano/Api/Experimental/Tx.hs
> +  )
This and `obtainCommonConstraints` should go to `Cardano.Api.Experimental.Eras` module, or another one with just constraints - it will be reused in the future most likely.

2024-08-08 12:23 UTC, carbolymer commented on cardano-api/internal/Cardano/Api/Experimental/Tx.hs
> +obtainShimConstraints BabbageEraOnwardsConway x = x
That should go to `Cardano.Api.Experimental.Eras` or a separate constraints module as well.

2024-08-08 12:30 UTC, carbolymer commented on cardano-api/internal/Cardano/Api/Experimental/Eras.hs
> +protocolVersionToSbe ConwayEra = ShelleyBasedEraConway
I'm not sure `protocolVersion` name fits well here. I'd suggest renaming this function to a dual name to `sbeToEra` indicating an opposite conversion:
```suggestion
eraToSbe
  :: Era era
  -> ShelleyBasedEra (AvailableErasToSbe era)
eraToSbe BabbageEra = ShelleyBasedEraBabbage
eraToSbe ConwayEra = ShelleyBasedEraConway
```

2024-08-09 13:21 UTC, Jimbo4350 commented on cardano-api/internal/Cardano/Api/Experimental/Eras.hs
> +data ConwayEra
I don't want to do this to avoid confusion with the api we are deprecating.

2024-08-09 13:25 UTC, smelc commented on cardano-api/internal/Cardano/Api/Experimental/Eras.hs
> +data ConwayEra
Same concern as @carbolymer :+1:

2024-08-09 13:29 UTC, smelc commented on cardano-api/internal/Cardano/Api/Experimental/Eras.hs
> +-- After a hardfork, the from which we hardfork from gets deprecated and
```suggestion
-- After a hardfork, the era from which we hardfork from gets deprecated and
```

2024-08-09 14:56 UTC, Jimbo4350 commented on cardano-api/internal/Cardano/Api/Experimental/Eras.hs
> +protocolVersionToSbe ConwayEra = ShelleyBasedEraConway
Yes this is a terrible name. It was a remnant of the initial idea which was to distinguish by the protocol version instead of the era.

2024-08-09 15:02 UTC, Jimbo4350 commented on cardano-api/internal/Cardano/Api/Experimental/Eras.hs
> +  ApiEraToExperimentalEra Api.ConwayEra = ConwayEra
So the issue here is we need to distinguish between:
- The new experimental api eras
- The existing api eras
- The ledger eras

I would keep this as `ApiEraToExperimentalEra` and change `AvailableErasToSbe` to `ExperimentalEraToApiEra`. The rename of `ToConstrainedLedgerEra` to `LedgerEra` is fine. Lmk what you think.

2024-08-09 15:03 UTC, Jimbo4350 commented on cardano-api/internal/Cardano/Api/Experimental/Eras.hs
> +  AvailableErasToSbe ConwayEra = Api.ConwayEra
https://github.com/IntersectMBO/cardano-api/pull/604#discussion_r1711638421

2024-08-09 15:03 UTC, Jimbo4350 commented on cardano-api/internal/Cardano/Api/Experimental/Eras.hs
> +  ToConstrainedLedgerEra ConwayEra = Ledger.Conway
https://github.com/IntersectMBO/cardano-api/pull/604#discussion_r1711638421

2024-08-09 15:45 UTC, Jimbo4350 commented on cardano-api/internal/Cardano/Api/Experimental/Eras.hs
> +sbeToEra :: ShelleyBasedEra era -> Either (DeprecatedEra era) (Era (ApiEraToExperimentalEra era))
`sbeToEra :: ShelleyBasedEra era -> Either (DeprecatedEra era) (Era era)` won't compile.

2024-08-12 15:06 UTC, Jimbo4350 commented on cardano-api/internal/Cardano/Api/Experimental/Eras.hs
> +data ConwayEra
> I think reusing type level tags will be much cleaner than introducing additional type families.

How will this avoid introducing additional type families?

2024-08-12 15:14 UTC, Jimbo4350 commented on cardano-api/internal/Cardano/Api/Experimental/Eras.hs
> +  ApiEraToExperimentalEra Api.ConwayEra = ConwayEra
Eventually the only type family that remains will be:
```

type family ApiEraToLedgerEra era = (r :: Type) | r -> era where
  ApiEraToLedgerEra Api.BabbageEra = Ledger.Babbage
  ApiEraToLedgerEra Api.ConwayEra = Ledger.Conway
```
The others are there to gradually introduce the change.

2024-08-12 16:03 UTC, smelc commented on cardano-api/internal/Cardano/Api/Experimental/Eras.hs
> +data ConwayEra
Note that my comment was unrelated to the need/avoidance for additional type families. I'm concerned by symbols having the exact same name, that are going to be disambiguated with different imports; and I suspect this will confuse both us and users (even more for the latter).

2024-08-12 16:17 UTC, Jimbo4350 commented on cardano-api/internal/Cardano/Api/Experimental/Eras.hs
> +data ConwayEra
Thinking about it some more I agree. We can re-use the types.

2024-08-22 09:10 UTC, carbolymer commented on cardano-api/internal/Cardano/Api/Fees.hs
> +{-# LANGUAGE UndecidableInstances #-}
Is this still needed?

2024-08-22 09:22 UTC, carbolymer commented on cardano-api/internal/Cardano/Api/Experimental/Eras.hs
> +  ApiEraToExperimentalEra Api.ConwayEra = ConwayEra
Yes I like the names you propose.

2024-08-22 09:23 UTC, carbolymer approved these changes

2024-08-23 15:37 UTC, merged