Add Inject instances for Eons. Deprecate old eons conversion functions.
IntersectMBO/cardano-api pull request #636
Opened 2024-09-13 07:34 UTC by carbolymer

# Changelog

```yaml
- description: |
    <insert-changelog-description-here>
# uncomment types applicable to the change:
  type:
  # - feature        # introduces a new feature
  # - breaking       # the API has changed in a breaking way
   - compatible     # the API has changed but is non-breaking
  # - optimisation   # measurable performance improvements
   - refactoring    # QoL changes
  # - bugfix         # fixes a defect
  # - test           # fixes/modifies tests
  # - maintenance    # not directly related to the code
  # - release        # related to a new release preparation
  # - documentation  # change in code docs, haddocks...
```

# Context

# Checklist

- [ ] Commit sequence broadly makes sense and commits have useful messages
- [ ] New tests are added if needed and existing tests are updated. See [Running tests](https://github.com/input-output-hk/cardano-node-wiki/wiki/Running-tests) for more details
- [ ] Self-reviewed the diff

2024-09-13 08:14 UTC, smelc approved these changes
Nice QoL change :+1:

2024-09-13 08:14 UTC, smelc commented on cardano-api/gen/Test/Gen/Cardano/Api/Typed.hs
> +  sbe = inject w :: ShelleyBasedEra era
```suggestion
  sbe :: ShelleyBasedEra era = inject w
```

Rationale: It's more common to have the type attached to the variable

2024-09-13 08:14 UTC, smelc commented on cardano-api/internal/Cardano/Api/Query/Expr.hs
> +      let sbe = inject era :: ShelleyBasedEra era
```suggestion
      let sbe :: ShelleyBasedEra era = inject era
```

2024-09-13 08:14 UTC, smelc commented on cardano-api/internal/Cardano/Api/Query/Expr.hs
> +  let sbe = inject era :: ShelleyBasedEra era
```suggestion
  let sbe :: ShelleyBasedEra era = inject era
```

2024-09-13 08:14 UTC, smelc commented on cardano-api/internal/Cardano/Api/Query/Expr.hs
> +  let sbe = inject era :: ShelleyBasedEra era
```suggestion
  let sbe :: ShelleyBasedEra era = inject era
```

2024-09-13 08:14 UTC, smelc commented on cardano-api/internal/Cardano/Api/Tx/Body.hs
> +  sbe = inject w :: ShelleyBasedEra era
```suggestion
  sbe :: ShelleyBasedEra era = inject w
```

2024-09-13 08:14 UTC, smelc commented on cardano-api/internal/Cardano/Api/Tx/Body.hs
> +  sbe = inject w :: ShelleyBasedEra era
```suggestion
  sbe :: ShelleyBasedEra era = inject w
```

2024-09-13 18:15 UTC, Jimbo4350 requested changes
Please explain the motivation behind this change. I don't see how this helps us. We are adding an additional step to the deprecation of these era conversion functions where what we should be doing is figuring out how to change the interface then deprecating and eventually remove the functions.

2024-09-16 20:55 UTC, carbolymer commented
@Jimbo4350 the goal of this PR is to make the codebase more pleasant to work with until we get rid of Eons. There's still some amount of work left to do, before we arrive there.

 I disagree that it adds an additional step in deprecation, I see `Inject` as a general purpose tool for total conversions between any two types. Those `Inject` instances would be gone together with `Eons` as well.

If you think this PR is changing too much, what do you think of just using `inject` in the glue code for experimental API. I mean the changes in `cardano-api/internal/Cardano/Api/Experimental/Eras.hs` ?

2024-11-13 12:51 UTC, Jimbo4350 approved these changes

2024-11-14 22:23 UTC, merged