Extra `HashableScriptData` in `TxBody` for PK inputs and reference inputs with hashed datums.
IntersectMBO/cardano-api pull request #637
Opened 2024-09-13 15:17 UTC by mmontin

This PR aims to solve issue #600 by allowing users to provide instances of `HashableScriptData` for hashed datums located:
* in reference inputs
* in regular inputs owned by private keys

For now, these data can only be provided:
* in outputs
* in regular inputs owned by scripts

This contribution intends to be as little invasive as possible, and to respect the current way of handling the creation of the data map provided in the script context. The map is currently built by browsing through the relevant parts of the body content and retrieving the relevant data there. Thus, the idea here is not to create a new field in the body content, but instead to allow user to add additional `HashableScriptData` at two addition locations in the body content.

2024-09-13 15:41 UTC, smelc commented on cardano-api/internal/Cardano/Api/Script.hs
> +    -> PrivateKeyWitness witctx era
Can you make this not a GADT? I know there are lots of them floating around but we are actually moving away from using GADTs when not needed.

2024-09-13 15:41 UTC, smelc commented on cardano-api/internal/Cardano/Api/Script.hs
> +  NoKeyDatumForStake :: KeyDatum WitCtxStake
Can you make this not a GADT? I know there are lots of them floating around but we are actually moving away from using GADTs when not needed.

2024-09-13 19:30 UTC, Jimbo4350 requested changes
Sorry this is not the cleanest approach to add this functionality. Myself and my team will handle this. Thank you for the attempt!

2024-09-14 13:29 UTC, mmontin commented on cardano-api/internal/Cardano/Api/Script.hs
> +    -> PrivateKeyWitness witctx era
Yes i can. I basically just mimicked how other types around were defined. But indeed GADTs are not necessary there.

2024-09-14 13:32 UTC, mmontin commented
@Jimbo4350 This was just the very beginning and I was in need for feedback but that's fine by me if you handle it.

2024-09-14 20:58 UTC, closed without merging

2024-09-17 14:58 UTC, Jimbo4350 commented
@mmontin https://github.com/IntersectMBO/cardano-api/pull/640