638-Allow next leadership-schedule at 4k/f
IntersectMBO/cardano-api pull request #639
Opened 2024-09-15 13:08 UTC by AndrewWestberg

# Changelog

```yaml
- description: |
    Allow next leadership-schedule at 4k/f
# uncomment types applicable to the change:
  type:
  # - feature        # introduces a new feature
  # - breaking       # the API has changed in a breaking way
  # - compatible     # the API has changed but is non-breaking
  # - optimisation   # measurable performance improvements
  # - refactoring    # QoL changes
  - bugfix         # fixes a defect
  # - test           # fixes/modifies tests
  # - maintenance    # not directly related to the code
  # - release        # related to a new release preparation
  # - documentation  # change in code docs, haddocks...
```

# Context

[Fixes 638](https://github.com/IntersectMBO/cardano-api/issues/638)

# How to trust this PR

It's a 1 number change from 3->4. It's trustworthy.

# Checklist

- [x] Commit sequence broadly makes sense and commits have useful messages
- [x] Self-reviewed the diff

2024-09-16 19:27 UTC, carbolymer requested changes

2024-09-16 19:27 UTC, carbolymer commented on cardano-api/internal/Cardano/Api/LedgerState.hs
> +        stabilityWindowR = fromIntegral (4 * sgSecurityParam sGen) / Ledger.unboundRational (sgActiveSlotsCoeff sGen)
This will break in Babbage, which is still used for example in cardano-testnet. You need to check which era you're in, using `sbe`. For example
```haskell
let stabilityWindowConst = caseShelleyToBabbageOrConwayEraOnwards (const 3) (const 4) sbe
```

2024-09-16 19:43 UTC, carbolymer commented
Reference for `4k/f` value in leadership selection in Conway: https://ouroboros-consensus.cardano.intersectmbo.org/docs/for-developers/Glossary#epoch-structure

2024-09-16 20:18 UTC, AndrewWestberg commented on cardano-api/internal/Cardano/Api/LedgerState.hs
> +        stabilityWindowR = fromIntegral (4 * sgSecurityParam sGen) / Ledger.unboundRational (sgActiveSlotsCoeff sGen)
fixed.

2024-09-17 11:28 UTC, carbolymer approved these changes

2024-09-18 08:45 UTC, carbolymer commented
@AndrewWestberg can you reformat your changes with:
```
./scripts/devshell/prettify cardano-api/internal/Cardano/Api/LedgerState.hs
```

2024-09-18 12:38 UTC, AndrewWestberg commented
> @AndrewWestberg can you reformat your changes with:
> 
> ```
> ./scripts/devshell/prettify cardano-api/internal/Cardano/Api/LedgerState.hs
> ```

This is completed.

2024-09-18 12:40 UTC, Jimbo4350 commented
> Reference for `4k/f` value in leadership selection in Conway: https://ouroboros-consensus.cardano.intersectmbo.org/docs/for-developers/Glossary#epoch-structure

@AndrewWestberg can you include a comment pointing to this and any other background regarding the `4k/f` value.

2024-09-18 12:41 UTC, Jimbo4350 approved these changes
LGTM - just one comment that needs to be addressed

2024-09-18 12:46 UTC, AndrewWestberg commented
> > Reference for `4k/f` value in leadership selection in Conway: https://ouroboros-consensus.cardano.intersectmbo.org/docs/for-developers/Glossary#epoch-structure
> 
> @AndrewWestberg can you include a comment pointing to this and any other background regarding the `4k/f` value.

This is resolved.

2024-09-20 18:20 UTC, merged