Remove redundant ScriptHash in ReferenceScript datatypes
IntersectMBO/cardano-api pull request #642
Opened 2024-09-23 19:28 UTC by Swordlash

# Changelog

```yaml
- description: |
    <insert-changelog-description-here>
  type:
  - breaking       
  - refactoring
```

# Context

Sometime ago I opened an issue #606 but I didn't get any response, so I've made a PR myself.
One of the members of my team asked why is the `Maybe ScriptHash` needed in the `PReferenceScript` and after some digging it seems it's completely redundant and not used anywhere (with the comment being obsolete). Therefore I removed it and everything "just compiled".

# Checklist

- [x] Commit sequence broadly makes sense and commits have useful messages
- [ ] New tests are added if needed and existing tests are updated. See [Running tests](https://github.com/input-output-hk/cardano-node-wiki/wiki/Running-tests) for more details
- [x] Self-reviewed the diff

2024-09-24 08:41 UTC, smelc commented
@Swordlash> can you fix the formatting of Haskell files? You need to run:

```shell
# order matters: fourmolu first, then stylish-haskell
fourmolu -i <modified files>
stylish-haskell -i <modified files>
```

2024-09-24 09:03 UTC, Swordlash commented
Formatting should be good now. Redundant whitespace it seems.

2024-09-24 12:25 UTC, carbolymer commented
@Swordlash can you squash the commits?
The change looks good for me, but I'll leave final approval to @Jimbo4350.

2024-09-24 12:31 UTC, carbolymer commented on cardano-api/internal/Cardano/Api/Script.hs
Those are used in
https://github.com/IntersectMBO/cardano-cli/blob/a157c492a4664b0ff4216e1c54a87c04adb0067b/cardano-cli/src/Cardano/CLI/EraBased/Run/Transaction.hs#L1381 to gather minting witnesses here: https://github.com/IntersectMBO/cardano-cli/blob/a157c492a4664b0ff4216e1c54a87c04adb0067b/cardano-cli/src/Cardano/CLI/EraBased/Run/Transaction.hs#L1364

2024-09-24 12:33 UTC, carbolymer requested changes
It's used in cardano-cli in handling of minting scripts.

2024-09-24 12:34 UTC, carbolymer commented on cardano-api/internal/Cardano/Api/Script.hs
> -      (Maybe ScriptHash)
The purpose of this field should be documented better.

2024-09-24 12:44 UTC, Swordlash commented on cardano-api/internal/Cardano/Api/Script.hs
This is some very unfortunate coupling, isn't it? Having a library keep redundant information (and confuse users) for the sake of one of downstream tools. Maybe we could refactor it out in `cardano-cli`?

2024-09-24 12:59 UTC, Swordlash commented on cardano-api/internal/Cardano/Api/Script.hs
Of course we can argue that if the user wants to reference a script then he probably knows the hash. If the above is not possible I would at least not make it `Maybe`, for the sake of API cleanliness.

2024-09-24 14:04 UTC, Swordlash commented on cardano-api/internal/Cardano/Api/Script.hs
@carbolymer I did the refactor, see the following: https://github.com/Swordlash/cardano-cli/commit/b5c76a012a0daa5d83dcce738dd25a1810b7b802

User provides the `Maybe PolicyId` himself anyway, so `cardano-cli` just temporarily stores this info in the `PReferenceScript` to be unpacked later. We can change the signature of the appropriate function to return a pair, so that we avoid storing the information in the datatype.

2024-09-26 09:29 UTC, Swordlash commented on cardano-api/internal/Cardano/Api/Script.hs
@carbolymer did you have a chance to take a look at the above? Tl;dr `cardano-cli` uses this field as a temporary container for user provided data and it can be safely refactored out.

2024-09-30 09:14 UTC, carbolymer commented on cardano-api/internal/Cardano/Api/Script.hs
Dzięki. Looks sensible. Would you mind opening a PR to cardano-cli with those changes?

2024-09-30 09:15 UTC, Swordlash commented on cardano-api/internal/Cardano/Api/Script.hs
Sure thing

2024-09-30 12:07 UTC, Swordlash commented on cardano-api/internal/Cardano/Api/Script.hs
@carbolymer here it is: https://github.com/IntersectMBO/cardano-cli/pull/918

2024-11-20 18:24 UTC, carbolymer commented
Superseded by 
- https://github.com/IntersectMBO/cardano-api/pull/663

2024-11-20 18:24 UTC, closed without merging