Expose functions and types from `cardano-ledger-alonzo` and `cardano-ledger-byron` required by cardano-cli
IntersectMBO/cardano-api pull request #647
Opened 2024-10-01 17:51 UTC by palas

# Changelog

```yaml
- description: |
    Exposed functions and types from cardano-ledger-alonzo, and cardano-ledger-byron required by cardano-cli
  type:
  - compatible     # the API has changed but is non-breaking
  - refactoring     # QoL changes
```

# Context

As part of the work targeted at addressing issues pointed out in https://github.com/IntersectMBO/cardano-api/issues/608, this PR aims to provide `cardano-cli` with everything it needs from ledger (in this PR `alonzo` and `byron` parts),

# How to trust this PR

Make sure it is just a refactoring.

Make sure the way new things are exposed is sensible.

Look at it in conjunction with: 

Take advantage that there are one commit for alonzo and one for byron (same for the corresponding PR in `cardano-cli`)

# Checklist

- [x] Commit sequence broadly makes sense and commits have useful messages
- [x] New tests are added if needed and existing tests are updated. See [Running tests](https://github.com/input-output-hk/cardano-node-wiki/wiki/Running-tests) for more details
- [x] Self-reviewed the diff

2024-10-02 08:22 UTC, smelc approved these changes
LGTM :clap: 

Thanks for the detailed _How to trust this PR_ instructions :100:

2024-10-03 13:20 UTC, Jimbo4350 requested changes

2024-10-03 13:20 UTC, Jimbo4350 commented on cardano-api/internal/Cardano/Api/ByronDelegation.hs
> +module Cardano.Api.ByronDelegation
Why? We have `Cardano.Api.Byron`. Let's expose everything `Byron` related there.

2024-10-03 13:20 UTC, Jimbo4350 commented on cardano-api/internal/Cardano/Api/ReexposeLedger.hs
> +  , Byron.Tx (..)
:+1:

2024-10-03 13:20 UTC, Jimbo4350 commented on cardano-api/internal/Cardano/Api/SpecialByron.hs
> +  , KeyHash
Should `KeyHash` be here?

2024-10-03 13:20 UTC, Jimbo4350 commented on cardano-api/internal/Cardano/Api/TxIn.hs
> +type ByronTxIn = Byron.TxIn
Let's create a separate module for Byron related things. We want to maintain a split between Byron and Shelley based eras.

2024-10-03 13:21 UTC, Jimbo4350 commented on cardano-api/internal/Cardano/Api/TxIn.hs
> +type ByronTxIn = Byron.TxIn
We can start with `Cardano.Api.Byron.Special` and `Cardano.Api.Byron.Misc`

2024-10-03 15:54 UTC, palas commented on cardano-api/internal/Cardano/Api/ByronDelegation.hs
> +module Cardano.Api.ByronDelegation
I was re-exporting from `internal`, because that is what everything in `Cardano.Api.Byron` does:
![image](https://github.com/user-attachments/assets/a75720d2-e8f1-413e-a804-c8a2acf3aa17)
But there is no reason why we cannot add a dependency to `cardano-ledger-byron` in the main project, that is probably simpler

2024-10-03 15:57 UTC, palas commented on cardano-api/internal/Cardano/Api/TxIn.hs
> +type ByronTxIn = Byron.TxIn
Ok, I will put everything in `Cardano.Api.Byron.Misc` as a first step

2024-10-03 18:09 UTC, Jimbo4350 requested changes

2024-10-03 18:09 UTC, Jimbo4350 commented on cardano-api/cardano-api.cabal
> +    Cardano.Api.Byron.Misc
We only want to expose `Cardano.Api.Byron` for now.

2024-10-03 18:12 UTC, Jimbo4350 commented on cardano-api/internal/Cardano/Api/ReexposeLedger.hs
> +  , Byron.Tx (..)
Apologies. We should move Byron related things to `Cardano.Api.Byron`.

2024-10-04 17:39 UTC, Jimbo4350 approved these changes
LGTM!

2024-10-04 18:35 UTC, merged