Add function to extract anchor data from certificate
IntersectMBO/cardano-api pull request #664
Opened 2024-10-25 14:02 UTC by palas

# Changelog

```yaml
- description: |
    - Add function to extract anchor data from a certificate
# uncomment types applicable to the change:
  type:
  # - feature        # introduces a new feature
  # - breaking       # the API has changed in a breaking way
  # - compatible     # the API has changed but is non-breaking
  # - optimisation   # measurable performance improvements
  # - refactoring    # QoL changes
  # - bugfix         # fixes a defect
  # - test           # fixes/modifies tests
  # - maintenance    # not directly related to the code
  # - release        # related to a new release preparation
  # - documentation  # change in code docs, haddocks...
```

# Context

This PR is part of addressing [this review comment](https://github.com/IntersectMBO/cardano-cli/pull/951#discussion_r1815183050). It moves the extracting of `anchor data` into `cardano-api` together with the rest of code that inspects certificates for easier maintenance.

# How to trust this PR

It is quite analogous to `filterUnRegDRepCreds`, except it does some conversion from `PoolMetadata` to `AnchorData` which are analogous types.

# Checklist

- [x] Commit sequence broadly makes sense and commits have useful messages
- [x] New tests are added if needed and existing tests are updated. See [Running tests](https://github.com/input-output-hk/cardano-node-wiki/wiki/Running-tests) for more details
- [x] Self-reviewed the diff

2024-10-25 18:04 UTC, Jimbo4350 requested changes
Let's stick with `Either` please. I don't want a mixture of `MonadError` and `Either`.

2024-10-28 08:06 UTC, carbolymer commented on cardano-api/internal/Cardano/Api/Certificate.hs
> +-- | Get anchor data hash from a certificate
Can you explain the returned value in the haddock, I mean when the `Nothing` is returned?

2024-10-28 08:11 UTC, carbolymer commented on cardano-api/internal/Cardano/Api/Certificate.hs
> +        Ledger.ShelleyTxCertDelegCert shelleyDelegCert ->
Can you use pattern synonyms, instead of the constructors here?

2024-10-28 21:34 UTC, palas commented on cardano-api/internal/Cardano/Api/Certificate.hs
> +        Ledger.ShelleyTxCertDelegCert shelleyDelegCert ->
Addressed here: https://github.com/IntersectMBO/cardano-api/pull/664/commits/acd50a481b8fd3dd6d236ecbe5017a51c98e9131

2024-10-28 21:34 UTC, palas commented on cardano-api/internal/Cardano/Api/Certificate.hs
> +-- | Get anchor data hash from a certificate
Addressed here: https://github.com/IntersectMBO/cardano-api/pull/664/commits/acd50a481b8fd3dd6d236ecbe5017a51c98e9131

2024-10-30 21:35 UTC, Jimbo4350 commented on cardano-api/internal/Cardano/Api/Certificate.hs
> +  = InvalidPoolMetadataHash Ledger.Url ByteString
I disagree with the name `AnchorDataFromCertificateException`. This is not really an exceptional circumstance.

2024-10-31 07:07 UTC, carbolymer commented on cardano-api/internal/Cardano/Api/Certificate.hs
> +  = InvalidPoolMetadataHash Ledger.Url ByteString
I agree. I think it should have an `Error` suffix. Also `Exception` instance isn't needed - we're not throwing it anywhere. I think we should only provide `Error` instance (with `prettyError`).

2024-10-31 07:19 UTC, carbolymer commented on cardano-api/internal/Cardano/Api/Certificate.hs
> +    :: (Ledger.ProtVerAtMost era 8, Ledger.ShelleyEraTxCert era)
```haskell
    :: (Ledger.ProtVerAtMost era 8, Ledger.ShelleyEraTxCert era)
```
A small nitpick: using a hardcoded `ProtVer` here is a leaking abstraction for me. I'd remove type signatures from `getAnchorDataFrom{Shelley,Conway}Certificate` altogether, because the functions are quite obvious in what they do.

Feel free to use your current version of the code if you like it better.

2024-10-31 10:57 UTC, palas commented on cardano-api/internal/Cardano/Api/Certificate.hs
> +  = InvalidPoolMetadataHash Ledger.Url ByteString
Addressed here: https://github.com/IntersectMBO/cardano-api/pull/664/commits/8c699b11232e32292900bcf5fe2b5111f30ec26b

2024-10-31 11:08 UTC, palas commented on cardano-api/internal/Cardano/Api/Certificate.hs
> +    :: (Ledger.ProtVerAtMost era 8, Ledger.ShelleyEraTxCert era)
Unfortunately it won't compile without a signature. But you are right, it is a leaking abstraction, so I will inline it. There should be a type that is abstract enough, but I couldn't find it

2024-10-31 11:12 UTC, palas commented on cardano-api/internal/Cardano/Api/Certificate.hs
> +    :: (Ledger.ProtVerAtMost era 8, Ledger.ShelleyEraTxCert era)
Addressed here: https://github.com/IntersectMBO/cardano-api/commit/240393bf8da6b0a315d7b6be275c934eabf64636

2024-11-04 12:57 UTC, Jimbo4350 approved these changes

2024-11-04 13:49 UTC, merged