Remove `Show (Some a)` and `Eq (Some a)`. Add a newtype `SomeSingletonType1` providing those instances using `deriving via`.
IntersectMBO/cardano-api pull request #665
Opened 2024-10-28 10:00 UTC by carbolymer

# Changelog

```yaml
- description: |
    Remove `Show (Some a)` and `Eq (Some a)`. Add a newtype `SomeSingletonType1` providing those instances using `deriving via`.
# uncomment types applicable to the change:
  type:
  # - feature        # introduces a new feature
  # - breaking       # the API has changed in a breaking way
  # - compatible     # the API has changed but is non-breaking
  # - optimisation   # measurable performance improvements
   - refactoring    # QoL changes
  # - bugfix         # fixes a defect
  # - test           # fixes/modifies tests
  # - maintenance    # not directly related to the code
  # - release        # related to a new release preparation
  # - documentation  # change in code docs, haddocks...
```

# Context

Additional context for the PR goes here. If the PR fixes a particular issue please provide a [link](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword=) to the issue.

# How to trust this PR

Highlight important bits of the PR that will make the review faster. If there are commands the reviewer can run to observe the new behavior, describe them.

# Checklist

- [ ] Commit sequence broadly makes sense and commits have useful messages
- [ ] New tests are added if needed and existing tests are updated. See [Running tests](https://github.com/input-output-hk/cardano-node-wiki/wiki/Running-tests) for more details
- [ ] Self-reviewed the diff

2024-10-28 12:29 UTC, Jimbo4350 requested changes

2024-10-28 12:29 UTC, Jimbo4350 commented on cardano-api/internal/Cardano/Api/Experimental/Eras.hs
> +newtype SomeSingletonType1 :: (k -> Type) -> Type where
Why? Is this being used anywhere?

2024-10-28 13:32 UTC, carbolymer commented on cardano-api/internal/Cardano/Api/Experimental/Eras.hs
> +newtype SomeSingletonType1 :: (k -> Type) -> Type where
In line 127.

2024-11-18 20:41 UTC, Jimbo4350 commented on cardano-api/internal/Cardano/Api/Experimental/Eras.hs
> +newtype SomeSingletonType1 :: (k -> Type) -> Type where
Why not:
```
diff --git a/cardano-api/internal/Cardano/Api/Experimental/Eras.hs b/cardano-api/internal/Cardano/Api/Experimental/Eras.hs
index fbf24a8f5..510c322f4 100644
--- a/cardano-api/internal/Cardano/Api/Experimental/Eras.hs
+++ b/cardano-api/internal/Cardano/Api/Experimental/Eras.hs
@@ -124,9 +124,11 @@ instance TestEquality Era where
 instance ToJSON (Era era) where
   toJSON = eraToStringLike
 
-deriving via (SomeSingletonType1 Era) instance Show (Some Era)
+instance Show (Some Era) where
+  showsPrec _ (Some era) = shows era
 
-deriving via (SomeSingletonType1 Era) instance Eq (Some Era)
+instance Eq (Some Era) where
+  Some era1 == Some era2 = isJust $ testEquality era1 era2
 
 instance Bounded (Some Era) where
   minBound = Some BabbageEra
```

2024-11-19 13:26 UTC, Jimbo4350 approved these changes

2024-11-19 22:14 UTC, merged