Integrate in preparation for `cardano-node` release `10.2.0`
IntersectMBO/cardano-api pull request #687
Opened 2024-11-21 02:07 UTC by neilmayhew

# Changelog

```yaml
- description: |
    Integrate `ouroboros-network`, `cardano-ledger` and `ouroboros-consensus`
    in preparation for `cardano-node` release `10.2.0`
  type:
   - release
```

# Context

See IntersectMBO/cardano-node#6040 for overall progress and links to PRs in other repos

# How to trust this PR

Similar changes have been made in `ouroboros-consensus`. Another commit is cherry-picked from #619.

# Checklist

- [x] Commit sequence broadly makes sense and commits have useful messages
- [ ] New tests are added if needed and existing tests are updated. See [Running tests](https://github.com/input-output-hk/cardano-node-wiki/wiki/Running-tests) for more details
- [x] Self-reviewed the diff

2025-01-08 15:48 UTC, neilmayhew commented
This will need to have the srp removed after new consensus packages are released to CHaP

2025-01-09 07:35 UTC, carbolymer requested changes
NTC version change looks problematic to me.

Can you clean up commits history please?

2025-01-09 07:35 UTC, carbolymer commented on cardano-api/internal/Cardano/Api/Query.hs
Where does this change come from? I believe those queries were introduced in the earlier eras.

This will probably break test networks which start in older eras and then hardfork to Conway.

2025-01-09 07:35 UTC, carbolymer commented on cardano-api/internal/Cardano/Api/Query.hs
> -  nodeToClientVersionOf QueryEpoch = NodeToClientV_9
Same comment as for `NodeToClientVersionOf (QueryInMode result)`

2025-01-09 07:35 UTC, carbolymer commented on cardano-api/internal/Cardano/Api/IPC.hs
> +        Net.connectTo
I'm wondering what's the purpose of the new return type of `connectTo`: `IO (Either SomeException a)`. Exceptions can be thrown in IO anyway...

2025-01-09 07:35 UTC, carbolymer commented on cardano-api/internal/Cardano/Api/Query.hs
> -  nodeToClientVersionOf QueryUTxOWhole = NodeToClientV_9
Same comment as for `NodeToClientVersionOf (QueryInMode result)`

2025-01-09 08:34 UTC, crocodile-dentist commented on cardano-api/internal/Cardano/Api/Query.hs
These changes are due to the fact that NodeToClientV_15 and earlier have been dropped from o-network.

2025-01-09 09:34 UTC, crocodile-dentist commented on cardano-api/internal/Cardano/Api/IPC.hs
> +        Net.connectTo
We distinguish between errors raised by a miniprotocol implementation, which are user defined arbitrary code, and general errors such as handshake errors etc. The former is returned in `Left` while the latter has to be caught manually.

2025-01-09 12:43 UTC, carbolymer commented on cardano-api/internal/Cardano/Api/Query.hs
Thanks. I'll double check if that's a blocker then and get back to you.

2025-01-09 13:44 UTC, neilmayhew commented
> Can you clean up commits history please?

@carbolymer What would you like changed? They're in a logical order and are labelled with the part of the integration that they apply to. However, perhaps you'd like to see some of them squashed. If so, could you let me know which ones?

2025-01-09 14:13 UTC, carbolymer commented on cardano-api/internal/Cardano/Api/Query.hs
Seems it's not. It's just a complication for the client side: https://ouroboros-consensus.cardano.intersectmbo.org/docs/for-developers/QueryVersioning#checks

2025-01-09 15:09 UTC, carbolymer commented on cardano-api/cardano-api.cabal
> +    hedgehog-extras >=0.6.1 && <0.6.5.1,
This is not needed anymore.
```suggestion
    hedgehog-extras >=0.6.1
```

2025-01-09 15:44 UTC, carbolymer approved these changes

2025-01-09 15:53 UTC, carbolymer commented
@neilmayhew Maybe it's too granular. But I don't have a big problem with it, we can keep it that way.

2025-01-09 16:42 UTC, neilmayhew commented
> @neilmayhew Maybe it's too granular. But I don't have a big problem with it, we can keep it that way.

It's a matter of taste, I guess. My own style is to be very fine grained, but I need to be reminded once in a while that this doesn't work for everybody :smile:

2025-01-10 07:36 UTC, merged

2025-01-10 07:37 UTC, carbolymer commented
Force merging since garnix was stuck and blocked the merge.