Added examples of transaction creation to Haddock
IntersectMBO/cardano-api pull request #698
Opened 2024-12-03 12:32 UTC by palas

# Changelog

```yaml
- description: |
    Added example of transaction creation with traditional and experimental APIs to Haddock.
# uncomment types applicable to the change:
  type:
  - test
  - documentation
```

# Context

Additional context for the PR goes here. If the PR fixes a particular issue please provide a [link](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword=) to the issue.

# How to trust this PR

Have a read of the haddock. Here is a render: 
[Cardano.Api.Experimental](https://github.com/user-attachments/files/17992874/Cardano.Api.Experimental.pdf)

# Checklist

- [x] Commit sequence broadly makes sense and commits have useful messages
- [x] New tests are added if needed and existing tests are updated. See [Running tests](https://github.com/input-output-hk/cardano-node-wiki/wiki/Running-tests) for more details
- [x] Self-reviewed the diff

2024-12-05 13:11 UTC, smelc approved these changes

2024-12-09 13:51 UTC, Jimbo4350 reviewed
Nice work :+1: . I would move the transaction creation haddocks to `Cardano.Api.Experimental.Tx` and point to it from here.

2024-12-09 13:51 UTC, Jimbo4350 commented on cardano-api/src/Cardano/Api/Experimental.hs
> +    -- towards using the new API and deprecating the old way, since the later is
later should be latter

2024-12-09 13:51 UTC, Jimbo4350 commented on cardano-api/src/Cardano/Api/Experimental.hs
> +    -- let sbe = Api.shelleyBasedEra :: Api.ShelleyBasedEra Api.ConwayEra
or we can use: `ShelleyBasedEraConway :: ShelleyBasedEra ConwayEra`.

2024-12-09 13:51 UTC, Jimbo4350 commented on cardano-api/src/Cardano/Api/Experimental.hs
> +    -- We can also derive it from 'ConwayEra' from 'Cardano.Api.Experimental' by using the 'convert' function:
So I think this is a bad UI. We should have a `defaultTxBodyContent` defined in an experimental module:
```
defaultTxBodyContent
  :: ()
  => Era era
  -> TxBodyContent BuildTx era
```

We want to avoid mixing the old api and the new api (but obviously allow for migration e.g via convert).

These haddocks are excellent but what we should do is have haddocks strictly describing the old api, the new api and how to migrate from the old to the new.

2024-12-09 13:51 UTC, Jimbo4350 commented on cardano-api/src/Cardano/Api/Experimental.hs
> +    -- ** Creating a 'TxBodyContent'
It's a shame you cannot import haddocks and have them render in multiple places. We also need this in  `Cardano.Api.Tx.Body`.

2024-12-09 13:51 UTC, Jimbo4350 commented on cardano-api/src/Cardano/Api/Experimental.hs
> +    -- let newApiSignedTx :: Ledger.Tx (Exp.LedgerEra Exp.ConwayEra) = Exp.signTx era [] [transactionWitness] unsignedTx
This transaction will not be balanced. We need to include how to do that. Perhaps adding haddocks to the `Cardano.Api.Fees` module and pointing at them from here.

2024-12-10 12:31 UTC, palas commented on cardano-api/src/Cardano/Api/Experimental.hs
> +    -- let sbe = Api.shelleyBasedEra :: Api.ShelleyBasedEra Api.ConwayEra
I was initially doing that, but it felt like breaking the abstraction

2024-12-10 12:44 UTC, palas commented on cardano-api/src/Cardano/Api/Experimental.hs
> +    -- towards using the new API and deprecating the old way, since the later is
Nice catch

2024-12-10 12:53 UTC, palas commented on cardano-api/src/Cardano/Api/Experimental.hs
> +    -- towards using the new API and deprecating the old way, since the later is
Addressed here: https://github.com/IntersectMBO/cardano-api/pull/698/commits/b33ebe4873cf6bdfa19699726f128ec9e2b38de7

2024-12-10 14:09 UTC, palas commented on cardano-api/src/Cardano/Api/Experimental.hs
> +    --               (Api.TxOutValueShelleyBased sbe (Api.inject (Ledger.Coin 10_000_000)))
Addressed here: https://github.com/IntersectMBO/cardano-api/pull/698/commits/ec017ee428c005ae4194fb9970e9f38f0f9ae8f0

2024-12-11 17:03 UTC, palas commented on cardano-api/src/Cardano/Api/Experimental.hs
> +    -- ** Creating a 'TxBodyContent'
Addressed here: https://github.com/IntersectMBO/cardano-api/pull/698/commits/526d3efc337275419679fc8fdb5a6ee9bc37d5be

Moved it to `Cardano.Api.Tx.Body` and pointed from `Cardano.Api.Experimental.Tx`.

Also solved this:

> I would move the transaction creation haddocks to Cardano.Api.Experimental.Tx and point to it from here.

2024-12-23 14:30 UTC, Jimbo4350 reviewed
Getting there :+1:

2024-12-23 14:30 UTC, Jimbo4350 commented on cardano-api/internal/Cardano/Api/Experimental/Tx.hs
> +    -- ** Creating a transaction using the old API
I would put this section in the old API.

2024-12-23 14:30 UTC, Jimbo4350 commented on cardano-api/internal/Cardano/Api/Experimental/Tx.hs
> +    -- ** Inspecting transactions
Same here. If it doesn't have to do with the new api, move it to the old api modules. The only thing we should be talking about with respect to the old api is how to convert between transactions from old and new.

2024-12-23 14:30 UTC, Jimbo4350 commented on cardano-api/internal/Cardano/Api/Fees.hs
> +    -- UTxO with exactly 12 ADA, and 2 ADA is enough for the fees, this could be a valid transaction. But still,
Not could be, it is a valid transaction. This working will be confusing to newcomers. 2 ADA is more than enough for fees on mainnet so I would talk about it in that context, say the transaction is valid but you are overspending on fees. You also need to talk about tx outputs to make the explanation clearer.

2024-12-23 14:30 UTC, Jimbo4350 commented on cardano-api/internal/Cardano/Api/Fees.hs
> +    -- balancing a draft transaciton, which require different amounts of information, and provide different levels
"transaction"

2024-12-23 14:30 UTC, Jimbo4350 commented on cardano-api/internal/Cardano/Api/Fees.hs
> +    --    For this example, we are assuming we are doing nothing like that and using not scripts,
"we are assuming we are only spending key locked UTxOs and so we can ignore the above"

2024-12-23 14:30 UTC, Jimbo4350 commented on cardano-api/internal/Cardano/Api/Fees.hs
> +    --     * The collateral amount we are depositing. This is only required for transactions that
that have _plutus scripts_.

2024-12-23 14:30 UTC, Jimbo4350 commented on cardano-api/internal/Cardano/Api/Fees.hs
> +    -- This will give us a balanced transaction, with the fees calculated, and the change output.
A balanced transaction body, that still needs to be signed.

2024-12-30 13:05 UTC, carbolymer commented on cardano-api/test/cardano-api-test/Test/Cardano/Api/Experimental.hs
> +          )
Can be simplified with `OverloadedLists`

```suggestion
              [
                ( srcTxId
                , Api.TxOut
                    changeAddress
                    (Api.lovelaceToTxOutValue sbe 12_000_000)
                    Api.TxOutDatumNone
                    Script.ReferenceScriptNone
                )
              ]
          
```

2024-12-30 13:06 UTC, carbolymer commented on cardano-api/test/cardano-api-test/Test/Cardano/Api/Experimental.hs
> +exampleProtocolParams :: Ledger.PParams (UnexportedLedger.ConwayEra Ledger.StandardCrypto)
This is fine, but I guess you could also use generator for protocol params here, might be a bit simpler and easier to maintain?

2024-12-30 13:13 UTC, carbolymer commented
Outside of the scope of this PR: Maybe could use [doctest](https://hackage.haskell.org/package/doctest) to make sure that haddock examples didn't bitrot?

2025-01-07 11:01 UTC, palas commented
> Outside of the scope of this PR: Maybe could use [doctest](https://hackage.haskell.org/package/doctest) to make sure that haddock examples didn't bitrot?

Yes, I was thinking the same. Currently it is not checked by the CI, but at least it is easy to update if we do. But I made a couple of examples like this in a different PR already.

2025-01-07 11:22 UTC, palas commented on cardano-api/test/cardano-api-test/Test/Cardano/Api/Experimental.hs
> +          )
Applied here: https://github.com/IntersectMBO/cardano-api/pull/698/commits/25e9c36f656b8d1283b080f37baee58c02a814c7

2025-01-07 11:32 UTC, palas commented on cardano-api/internal/Cardano/Api/Fees.hs
> +    --     * The collateral amount we are depositing. This is only required for transactions that
Addressed here: https://github.com/IntersectMBO/cardano-api/commit/7c09d6f5adf9c271e2fc30581f8fc571a75ece34

2025-01-07 11:38 UTC, palas commented on cardano-api/internal/Cardano/Api/Fees.hs
> +    --    For this example, we are assuming we are doing nothing like that and using not scripts,
Addressed here: https://github.com/IntersectMBO/cardano-api/commit/d4faeb6e08448a0c6ff0f306bf31e645bb49d6a3

2025-01-07 11:40 UTC, palas commented on cardano-api/internal/Cardano/Api/Fees.hs
> +    -- balancing a draft transaciton, which require different amounts of information, and provide different levels
Addressed here: https://github.com/IntersectMBO/cardano-api/commit/799c86e7a214fd07a9aafba4ec344f6485958934

2025-01-07 11:54 UTC, palas commented on cardano-api/internal/Cardano/Api/Fees.hs
> +    -- UTxO with exactly 12 ADA, and 2 ADA is enough for the fees, this could be a valid transaction. But still,
Addressed here: https://github.com/IntersectMBO/cardano-api/commit/328840873eb8fefd70648e1829e37b56498c1230

2025-01-07 17:19 UTC, palas commented on cardano-api/internal/Cardano/Api/Experimental/Tx.hs
> +    -- ** Inspecting transactions
Addressed here: https://github.com/IntersectMBO/cardano-api/commit/9ae784b65f133178deb0c050e447dda9f284ce4b

2025-01-07 17:20 UTC, palas commented on cardano-api/internal/Cardano/Api/Tx/Body.hs
> +  ( -- * Creating a 'TxBodyContent'
Addressed here: https://github.com/IntersectMBO/cardano-api/commit/9ae784b65f133178deb0c050e447dda9f284ce4b

2025-01-08 12:31 UTC, palas commented on cardano-api/internal/Cardano/Api/Experimental/Tx.hs
> +    -- If we have a UTxO with exactly 12 ADA, and 2 ADA is enough for the fees, we could just construct
It seems the only change is about multi-asset like you say:
<img width="567" alt="image" src="https://github.com/user-attachments/assets/7ab4a668-74c6-4933-b67d-a6c3eef0579c" />
So we just need to mention that you can mint (or destroy, which is considered minting negatively) assets (other than ADA), and that also affects the balance.

2025-01-08 13:55 UTC, palas commented on cardano-api/internal/Cardano/Api/Experimental/Tx.hs
> +    -- If we have a UTxO with exactly 12 ADA, and 2 ADA is enough for the fees, we could just construct
Because there is two references I clarified this in `Fees.hs` instead. Here: https://github.com/IntersectMBO/cardano-api/pull/698/commits/390d6a9a2cde391e0b9f8ea63df58869ddb229b1

2025-02-11 17:33 UTC, palas commented
Backup: https://github.com/IntersectMBO/cardano-api/tree/backup/haddock-for-experimental-api

2025-02-12 15:02 UTC, Jimbo4350 requested changes

2025-02-12 15:02 UTC, Jimbo4350 commented on cardano-api/src/Cardano/Api/Experimental.hs
> +    -- check the documentation of the module "Cardano.Api.Experimental.Tx".
This link is still broken

2025-02-12 15:06 UTC, Jimbo4350 commented on cardano-api/src/Cardano/Api/Experimental.hs
> +    -- * Contents
Remove Contents

2025-02-12 15:10 UTC, Jimbo4350 commented on cardano-api/src/Cardano/Api/Internal/Experimental/Tx.hs
> +    -- You can find a compilable version of these examples in "Test.Cardano.Api.Experimental".
This link is broken

2025-02-12 15:10 UTC, Jimbo4350 commented on cardano-api/src/Cardano/Api/Internal/Experimental/Tx.hs
> +    -- previous section directly, and it would be a valid transaction, but:
What previous section?

2025-02-12 15:11 UTC, Jimbo4350 commented on cardano-api/src/Cardano/Api/Internal/Experimental/Tx.hs
> +    -- You can see how to create a 'ShelleyWitnessSigningKey' in the documentation of the "Cardano.Api.Tx.Sign" module.
Broken link

2025-02-12 18:09 UTC, Jimbo4350 commented on cardano-api/src/Cardano/Api/Internal/Fees.hs
> +    -- us to send the amount we want to send, pay only the necessary fees (or little more), and it
Remove "(or a little more)".

2025-02-12 18:09 UTC, Jimbo4350 commented on cardano-api/src/Cardano/Api/Internal/Fees.hs
> +    -- * 0.2 ADA in fees
This would be an overestimation of the fees right? You need to point this out.

2025-02-12 18:12 UTC, Jimbo4350 requested changes
Most of the links to modules are broken. We need to fix this. I also need you to work with @olgahryniuk to improve the flow of the documentation.

2025-02-13 09:20 UTC, palas commented on cardano-api/src/Cardano/Api/Internal/Experimental/Tx.hs
> +    -- You can find a compilable version of these examples in "Test.Cardano.Api.Experimental".
This one I will probably just make it text instead of a link. Because it is in the `test` package, and I mean people to look at the code not the Haddock.

2025-02-13 09:24 UTC, palas commented on cardano-api/src/Cardano/Api/Internal/Experimental/Tx.hs
> +    -- previous section directly, and it would be a valid transaction, but:
I meant the `Creating a 'TxBodyContent'` section, but since that section is essentially a pointer, I may as well point directly to `Cardano.Api.Internal.Tx.Body`.

2025-02-13 10:36 UTC, palas commented on cardano-api/src/Cardano/Api/Experimental.hs
> +    -- check the documentation of the module "Cardano.Api.Experimental.Tx".
Addressed all in: https://github.com/IntersectMBO/cardano-api/pull/698/commits/7d3ba154570db88a34f3b2897c808b360d4672bb

2025-02-13 11:00 UTC, carbolymer commented
FYI https://github.com/IntersectMBO/cardano-api/actions/workflows/github-page.yml has a trigger, where you can specify a branch. It'll produce an artifact with haddocks. E.g.: https://github.com/IntersectMBO/cardano-api/actions/runs/13306164579

2025-02-20 12:24 UTC, olgahryniuk approved these changes
Several typos to fix, please.

2025-02-20 12:24 UTC, olgahryniuk commented on cardano-api/src/Cardano/Api/Experimental.hs
> +    -- see the module "Cardano.Api.Internal.Experimental.Tx" documentation.
```suggestion
    -- see the "Cardano.Api.Internal.Experimental.Tx" documentation.
```

2025-02-20 12:24 UTC, olgahryniuk commented on cardano-api/src/Cardano/Api/Internal/Experimental/Tx.hs
> +    -- In the following examples, the following qualified modules are used:
```suggestion
    -- In the examples below, the following qualified modules are used:
```

2025-02-20 12:24 UTC, olgahryniuk commented on cardano-api/src/Cardano/Api/Internal/Experimental/Tx.hs
> +    -- In the following examples, the following qualified modules are used:
To avoid repetition - I missed this during the initial review.

2025-02-20 12:24 UTC, olgahryniuk commented on cardano-api/src/Cardano/Api/Internal/Experimental/Tx.hs
> +    -- "Cardano.Api.Internal.Tx.Body", and it would be a valid. However:
```suggestion
    -- "Cardano.Api.Internal.Tx.Body", and it would be valid. However:
```

2025-02-20 12:24 UTC, olgahryniuk commented on cardano-api/src/Cardano/Api/Internal/Experimental/Tx.hs
> +    -- A transaction created with the new API can beeasily converted to the old API by
```suggestion
    -- A transaction created with the new API can be easily converted to the old API by
```

2025-02-20 12:24 UTC, olgahryniuk commented on cardano-api/src/Cardano/Api/Internal/Tx/Sign.hs
> +    -- Signing a transaction requires a witness -- for example, a 'ShelleyWitnessSigningKey'.
```suggestion
    -- Signing a transaction requires a witness, for example, a 'ShelleyWitnessSigningKey'.
```

2025-02-20 12:24 UTC, olgahryniuk commented on cardano-api/src/Cardano/Api/Internal/Tx/Body.hs
> +    -- the old way to ensure simpliciy, closer alignment with the ledger, and
```suggestion
    -- the old way to ensure simplicity, closer alignment with the ledger, and
```

2025-02-20 12:24 UTC, olgahryniuk commented on cardano-api/src/Cardano/Api/Internal/Tx/Body.hs
> +    -- we you are working with. For example, if you are working with the 'ConwayEra', use 'shelleyBasedEra'
```suggestion
    -- you are working with. For example, if you are working with the 'ConwayEra', use 'shelleyBasedEra'
```

2025-02-20 12:24 UTC, olgahryniuk commented on cardano-api/src/Cardano/Api/Internal/Tx/Body.hs
> +    -- Note to se the transaction fee. For example, set it to 2 ada:
```suggestion
    -- Note to set the transaction fee. For example, set it to 2 ada:
```

2025-02-20 12:24 UTC, olgahryniuk commented on cardano-api/src/Cardano/Api/Internal/Tx/Body.hs
> +    -- Signing a transaction requires a witness -- for example, a 'ShelleyWitnessSigningKey'.
```suggestion
    -- Signing a transaction requires a witness, for example, a 'ShelleyWitnessSigningKey'.
```

2025-02-20 12:44 UTC, olgahryniuk reviewed
Final suggestions

2025-02-20 12:44 UTC, olgahryniuk commented on cardano-api/src/Cardano/Api/Internal/Fees.hs
> +    -- However, we don't always want to spend all the ada from a UTxO. Balancing a transaction ensures
```suggestion
    -- However, we don't always want to spend all the ada from a UTXO. Balancing a transaction ensures
```

2025-02-20 12:44 UTC, olgahryniuk commented on cardano-api/src/Cardano/Api/Internal/Fees.hs
> +    -- * 0.2 ada in fees (calculated fees, in this case, an overestimation)
```suggestion
    -- * 0.2 ada in fees (calculated fees, in this case, an overestimation).
```

2025-02-20 12:44 UTC, olgahryniuk commented on cardano-api/src/Cardano/Api/Internal/Fees.hs
> +    -- Alternatively, we can get it from our signing key
```suggestion
    -- Alternatively, we can get it from our signing key:
```

2025-02-20 12:44 UTC, olgahryniuk commented on cardano-api/src/Cardano/Api/Internal/Fees.hs
> +    -- 7. Finally, we need the total amount of ada (and other tokens) in the UTxOs being spent. In this example,
```suggestion
    -- 7. Finally, we need the total amount of ada (and other tokens) in the UTXOs being spent. In this example,
```

2025-02-20 12:44 UTC, olgahryniuk commented on cardano-api/src/Cardano/Api/Internal/Fees.hs
> +    -- 1. Shelley-based era witness for thecurrent era, retrievable using 'shelleyBasedEra'.
```suggestion
    -- 1. Shelley-based era witness for the current era, retrievable using 'shelleyBasedEra'.
```

2025-02-21 15:07 UTC, Jimbo4350 approved these changes
LGTM :+1: . A few comments need to be addressed and the commits should be squashed.

2025-02-21 15:17 UTC, palas commented
> Outside of the scope of this PR: Maybe could use [doctest](https://hackage.haskell.org/package/doctest) to make sure that haddock examples didn't bitrot?

https://github.com/IntersectMBO/cardano-api/issues/760

2025-02-21 15:21 UTC, palas commented on cardano-api/src/Cardano/Api/Internal/Experimental/Eras.hs
> +-- | An existential wrapper for types of kind @k -> Types@. It can hold any
Addressed here: https://github.com/IntersectMBO/cardano-api/commit/c1008b2b6afd94b034b6083e127e8895c74f5330

2025-02-21 15:24 UTC, palas commented on cardano-api/src/Cardano/Api/Internal/Experimental/Eras.hs
> +-- | Represents Cardano blockchain eras, including those currently on mainnet
Addressed here: https://github.com/IntersectMBO/cardano-api/commit/bfb4ec35a5b18d2f52e0c0657384c0fd04b00792

2025-02-21 15:31 UTC, palas commented on cardano-api/src/Cardano/Api/Internal/Experimental/Eras.hs
> +-- After a hard fork, the era is deprecated and removed
Addressed here: https://github.com/IntersectMBO/cardano-api/commit/aa43ad498788d894f8ad7a9734174efde9394019

2025-02-21 15:35 UTC, palas commented on cardano-api/src/Cardano/Api/Internal/Tx/Body.hs
> +    -- the lenses 'getTxBody' and 'getTxWitnesses' respectively, from "Cardano.Api".
Addressed here: https://github.com/IntersectMBO/cardano-api/commit/71157a7cf968521aff10907d5985bc10d9eebabd

2025-02-21 15:39 UTC, palas commented
https://github.com/IntersectMBO/cardano-api/tree/backup/haddock-for-experimental-api

2025-02-21 17:07 UTC, Jimbo4350 commented
This comment has not be addressed: https://github.com/IntersectMBO/cardano-api/pull/698#discussion_r1965602518

2025-02-21 17:09 UTC, Jimbo4350 requested changes
I guess I was not clear enough. Address the comments please before merging.

2025-02-21 17:13 UTC, Jimbo4350 approved these changes

2025-02-21 17:27 UTC, merged