Add module for UTxO type and operations
IntersectMBO/cardano-api pull request #710
Opened 2024-12-13 18:58 UTC by locallycompact

# Changelog

```yaml
- description: |
    Add `Cardano.Api.UTxO` module for common UTxO operations.
# uncomment types applicable to the change:
  type:
  - feature        # introduces a new feature
  # - breaking       # the API has changed in a breaking way
  - compatible     # the API has changed but is non-breaking
  # - optimisation   # measurable performance improvements
  # - refactoring    # QoL changes
  # - bugfix         # fixes a defect
  # - test           # fixes/modifies tests
  # - maintenance    # not directly related to the code
  # - release        # related to a new release preparation
  # - documentation  # change in code docs, haddocks...
```

# Context

Additional context for the PR goes here. If the PR fixes a particular issue please provide a [link](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword=) to the issue.

# How to trust this PR

Highlight important bits of the PR that will make the review faster. If there are commands the reviewer can run to observe the new behavior, describe them.

# Checklist

- [ ] Commit sequence broadly makes sense and commits have useful messages
- [ ] New tests are added if needed and existing tests are updated. See [Running tests](https://github.com/input-output-hk/cardano-node-wiki/wiki/Running-tests) for more details
- [ ] Self-reviewed the diff

2024-12-30 13:00 UTC, carbolymer reviewed
LGTM, @Jimbo4350 thoughts?

2024-12-30 13:00 UTC, carbolymer commented on cardano-api/internal/Cardano/Api/Query/UTxO.hs
> +fromPairs = UTxO . Map.fromList
An instance of `IsList` can be provided to avoid the need of having a specialised function.

2024-12-30 13:00 UTC, carbolymer commented on cardano-api/internal/Cardano/Api/Query/UTxO.hs
> +newtype UTxO era = UTxO {unUTxO :: Map TxIn (TxOut CtxUTxO era)}
An instance of `MonoTraversable (UTxO era)` would be useful here.

2024-12-30 13:00 UTC, carbolymer commented on cardano-api/internal/Cardano/Api/Query/UTxO.hs
> +pairs = Map.toList . unUTxO
Redundant, if `IsList (UTxO era)` is provided

2025-01-03 15:33 UTC, locallycompact commented
8.10 doesn't support IsList so this is a bit awkward.

2025-01-07 08:50 UTC, carbolymer commented on cardano-api/internal/Cardano/Api/Query/UTxO.hs
> +{-# LANGUAGE UndecidableInstances #-}
Why `UndecidableInstances` is needed?

2025-01-07 11:57 UTC, locallycompact commented on cardano-api/internal/Cardano/Api/Query/UTxO.hs
> +{-# LANGUAGE UndecidableInstances #-}
Apparently

```
internal/Cardano/Api/Query/UTxO.hs:29:20: error: [GHC-22979]
    • The type-family application ‘Item (Map TxIn (TxOut CtxUTxO era))’
        is no smaller than the LHS of the family instance ‘Item (UTxO era)’
    • In the instance declaration for ‘IsList (UTxO era)’
    Suggested fix: Perhaps you intended to use UndecidableInstances
   |
29 |   deriving newtype IsList
   |                    ^^^^^^
```

2025-01-27 11:20 UTC, locallycompact commented on cardano-api/internal/Cardano/Api/Query/UTxO.hs
> +{-# LANGUAGE UndecidableInstances #-}
@carbolymer Can we resolve this? Is something weird here?

2025-01-29 14:43 UTC, carbolymer commented on cardano-api/internal/Cardano/Api/Query/UTxO.hs
> +{-# LANGUAGE UndecidableInstances #-}
Sorry, I've missed GH notification about your message. Let's leave it.

2025-01-29 15:07 UTC, Jimbo4350 commented on cardano-api/internal/Cardano/Api/Query/UTxO.hs
> +resolve :: TxIn -> UTxO era -> Maybe (TxOut CtxUTxO era)
why `resolve` as well?

2025-01-29 15:07 UTC, Jimbo4350 commented on cardano-api/cardano-api.cabal
> +    Cardano.Api.UTxO
Keep this module hidden and expose the functionality from `Cardano.Api.` We need to do an audit on how we expose things.

2025-01-29 15:40 UTC, locallycompact commented on cardano-api/cardano-api.cabal
> +    Cardano.Api.UTxO
No. This module by design is intended to be imported qualified, similar to container modules such as `Data.Map`, as it contains function names which commonly conflict.

2025-01-29 15:41 UTC, locallycompact commented on cardano-api/src/Cardano/Api/UTxO.hs
> +module Cardano.Api.UTxO (module Cardano.Api.Query.UTxO) where
Also see above.

2025-01-29 15:41 UTC, locallycompact commented on cardano-api/internal/Cardano/Api/Query/UTxO.hs
> +resolve :: TxIn -> UTxO era -> Maybe (TxOut CtxUTxO era)
Yes this could be dropped.

2025-01-31 11:54 UTC, Jimbo4350 commented on cardano-api/cardano-api.cabal
> +    Cardano.Api.UTxO
Yes. This PR will remain unmerged until this change is made

2025-01-31 11:54 UTC, Jimbo4350 commented on cardano-api/src/Cardano/Api/UTxO.hs
> +module Cardano.Api.UTxO (module Cardano.Api.Query.UTxO) where
Likewise, this PR will remain unmerged until this change is made.

2025-01-31 11:55 UTC, Jimbo4350 requested changes
Two changes need to be made

2025-02-04 14:56 UTC, locallycompact commented on cardano-api/cardano-api.cabal
> +    Cardano.Api.UTxO
OK. Didn't mean to sound presumptuous, I assumed we were misunderstanding each other. If I do understand you correctly, do you mean to expose functions such as `empty` and `lookup` directly through `Cardano.Api`? What I was trying to do here is provide a qualified import that deals with only this container type, because that is clear to the reader, eg `import Cardano.Api.UTxO as UTxO`, and called as `UTxO.empty`, `UTxO.lookup`. Doing `import qualified Cardano.Api as UTxO` is confusing, as it would contain functions that don't concern UTxOs, and `import qualified Cardano.Api as Api` would also be confusing, as `Api.empty` requires context for the reader when reading at the call site. Can you confirm if this is what you meant?

2025-02-07 13:30 UTC, carbolymer commented on cardano-api/cardano-api.cabal
> +    Cardano.Api.UTxO
I agree here with @locallycompact . Exposing commonly used function names like `empty` or `singleton` through `Cardano.Api` will be annoying. End users will be forced to qualify `Cardano.Api` imports. Moreover, if we decide to provide another similar container utility the same way in cardano-api, then the names will be in use already, and we'll be forced to use different names e.g. `emptyTxSet`, `lookupTxSet` ...

2025-02-07 14:05 UTC, Jimbo4350 commented on cardano-api/cardano-api.cabal
> +    Cardano.Api.UTxO
@locallycompact Fair point.

@carbolymer  I'd like to task you with writing an ADR as to how we should expose `cardano-api`'s functionality. As it has been sub optimal for a long time.

2025-02-07 14:05 UTC, Jimbo4350 approved these changes

2025-02-07 14:53 UTC, carbolymer commented on cardano-api/cardano-api.cabal
> +    Cardano.Api.UTxO
Or we could pick a middle ground here: export just the `UTxO` type and its instances through `Cardano.Api`, the utility functions should stay in the `UTxO` module exported from `cardano-api`.

2025-02-07 18:45 UTC, locallycompact commented on cardano-api/cardano-api.cabal
> +    Cardano.Api.UTxO
@carbolymer I think that's the current behaviour

2025-02-10 10:14 UTC, carbolymer commented
Can you place the new UTxO module in `Cardano.Api.Tx.UTxO`? The cabal package is fine. We're shifting modules a bit in https://github.com/IntersectMBO/cardano-api/pull/748/ so it'll better suit there I think.

2025-02-10 11:21 UTC, locallycompact commented
I will rebase after that work.

2025-02-12 15:13 UTC, carbolymer approved these changes

2025-02-14 15:25 UTC, merged